XEVT(_T("WM_NULL"),WM_NULL,0x0000)
XEVT(_T("WM_CREATE"),WM_CREATE,0x0001)
XEVT(_T("WM_DESTROY"),WM_DESTROY,0x0002)
XEVT(_T("WM_MOVE"),WM_MOVE,0x0003)
XEVT(_T("WM_SIZE"),WM_SIZE,0x0005)

XEVT(_T("WM_ACTIVATE"),WM_ACTIVATE,0x0006)

XEVT(_T("WM_SETFOCUS"),WM_SETFOCUS,0x0007)
XEVT(_T("WM_KILLFOCUS"),WM_KILLFOCUS,0x0008)
XEVT(_T("WM_ENABLE"),WM_ENABLE,0x000A)
XEVT(_T("WM_SETREDRAW"),WM_SETREDRAW,0x000B)
XEVT(_T("WM_SETTEXT"),WM_SETTEXT,0x000C)
XEVT(_T("WM_GETTEXT"),WM_GETTEXT,0x000D)
XEVT(_T("WM_GETTEXTLENGTH"),WM_GETTEXTLENGTH,0x000E)
XEVT(_T("WM_PAINT"),WM_PAINT,0x000F)
XEVT(_T("WM_CLOSE"),WM_CLOSE,0x0010)

XEVT(_T("WM_QUERYENDSESSION"),WM_QUERYENDSESSION,0x0011)
XEVT(_T("WM_QUERYOPEN"),WM_QUERYOPEN,0x0013)
XEVT(_T("WM_ENDSESSION"),WM_ENDSESSION,0x0016)

XEVT(_T("WM_QUIT"),WM_QUIT,0x0012)
XEVT(_T("WM_ERASEBKGND"),WM_ERASEBKGND,0x0014)
XEVT(_T("WM_SYSCOLORCHANGE"),WM_SYSCOLORCHANGE,0x0015)
XEVT(_T("WM_SHOWWINDOW"),WM_SHOWWINDOW,0x0018)
XEVT(_T("WM_WININICHANGE"),WM_WININICHANGE,0x001A)

XEVT(_T("WM_SETTINGCHANGE"),WM_SETTINGCHANGE,WM_WININICHANGE)



XEVT(_T("WM_DEVMODECHANGE"),WM_DEVMODECHANGE,0x001B)
XEVT(_T("WM_ACTIVATEAPP"),WM_ACTIVATEAPP,0x001C)
XEVT(_T("WM_FONTCHANGE"),WM_FONTCHANGE,0x001D)
XEVT(_T("WM_TIMECHANGE"),WM_TIMECHANGE,0x001E)
XEVT(_T("WM_CANCELMODE"),WM_CANCELMODE,0x001F)
XEVT(_T("WM_SETCURSOR"),WM_SETCURSOR,0x0020)
XEVT(_T("WM_MOUSEACTIVATE"),WM_MOUSEACTIVATE,0x0021)
XEVT(_T("WM_CHILDACTIVATE"),WM_CHILDACTIVATE,0x0022)
XEVT(_T("WM_QUEUESYNC"),WM_QUEUESYNC,0x0023)

XEVT(_T("WM_GETMINMAXINFO"),WM_GETMINMAXINFO,0x0024)

XEVT(_T("WM_PAINTICON"),WM_PAINTICON,0x0026)
XEVT(_T("WM_ICONERASEBKGND"),WM_ICONERASEBKGND,0x0027)
XEVT(_T("WM_NEXTDLGCTL"),WM_NEXTDLGCTL,0x0028)
XEVT(_T("WM_SPOOLERSTATUS"),WM_SPOOLERSTATUS,0x002A)
XEVT(_T("WM_DRAWITEM"),WM_DRAWITEM,0x002B)
XEVT(_T("WM_MEASUREITEM"),WM_MEASUREITEM,0x002C)
XEVT(_T("WM_DELETEITEM"),WM_DELETEITEM,0x002D)
XEVT(_T("WM_VKEYTOITEM"),WM_VKEYTOITEM,0x002E)
XEVT(_T("WM_CHARTOITEM"),WM_CHARTOITEM,0x002F)
XEVT(_T("WM_SETFONT"),WM_SETFONT,0x0030)
XEVT(_T("WM_GETFONT"),WM_GETFONT,0x0031)
XEVT(_T("WM_SETHOTKEY"),WM_SETHOTKEY,0x0032)
XEVT(_T("WM_GETHOTKEY"),WM_GETHOTKEY,0x0033)
XEVT(_T("WM_QUERYDRAGICON"),WM_QUERYDRAGICON,0x0037)
XEVT(_T("WM_COMPAREITEM"),WM_COMPAREITEM,0x0039)

XEVT(_T("WM_GETOBJECT"),WM_GETOBJECT,0x003D)

XEVT(_T("WM_COMPACTING"),WM_COMPACTING,0x0041)
XEVT(_T("WM_COMMNOTIFY"),WM_COMMNOTIFY,0x0044)  
XEVT(_T("WM_WINDOWPOSCHANGING"),WM_WINDOWPOSCHANGING,0x0046)
XEVT(_T("WM_WINDOWPOSCHANGED"),WM_WINDOWPOSCHANGED,0x0047)

XEVT(_T("WM_POWER"),WM_POWER,0x0048)

XEVT(_T("WM_COPYDATA"),WM_COPYDATA,0x004A)
XEVT(_T("WM_CANCELJOURNAL"),WM_CANCELJOURNAL,0x004B)

XEVT(_T("WM_NOTIFY"),WM_NOTIFY,0x004E)
XEVT(_T("WM_INPUTLANGCHANGEREQUEST"),WM_INPUTLANGCHANGEREQUEST,0x0050)
XEVT(_T("WM_INPUTLANGCHANGE"),WM_INPUTLANGCHANGE,0x0051)
XEVT(_T("WM_TCARD"),WM_TCARD,0x0052)
XEVT(_T("WM_HELP"),WM_HELP,0x0053)
XEVT(_T("WM_USERCHANGED"),WM_USERCHANGED,0x0054)
XEVT(_T("WM_NOTIFYFORMAT"),WM_NOTIFYFORMAT,0x0055)

XEVT(_T("WM_CONTEXTMENU"),WM_CONTEXTMENU,0x007B)
XEVT(_T("WM_STYLECHANGING"),WM_STYLECHANGING,0x007C)
XEVT(_T("WM_STYLECHANGED"),WM_STYLECHANGED,0x007D)
XEVT(_T("WM_DISPLAYCHANGE"),WM_DISPLAYCHANGE,0x007E)
XEVT(_T("WM_GETICON"),WM_GETICON,0x007F)
XEVT(_T("WM_SETICON"),WM_SETICON,0x0080)

XEVT(_T("WM_NCCREATE"),WM_NCCREATE,0x0081)
XEVT(_T("WM_NCDESTROY"),WM_NCDESTROY,0x0082)
XEVT(_T("WM_NCCALCSIZE"),WM_NCCALCSIZE,0x0083)
XEVT(_T("WM_NCHITTEST"),WM_NCHITTEST,0x0084)
XEVT(_T("WM_NCPAINT"),WM_NCPAINT,0x0085)
XEVT(_T("WM_NCACTIVATE"),WM_NCACTIVATE,0x0086)
XEVT(_T("WM_GETDLGCODE"),WM_GETDLGCODE,0x0087)

XEVT(_T("WM_SYNCPAINT"),WM_SYNCPAINT,0x0088)

XEVT(_T("WM_NCMOUSEMOVE"),WM_NCMOUSEMOVE,0x00A0)
XEVT(_T("WM_NCLBUTTONDOWN"),WM_NCLBUTTONDOWN,0x00A1)
XEVT(_T("WM_NCLBUTTONUP"),WM_NCLBUTTONUP,0x00A2)
XEVT(_T("WM_NCLBUTTONDBLCLK"),WM_NCLBUTTONDBLCLK,0x00A3)
XEVT(_T("WM_NCRBUTTONDOWN"),WM_NCRBUTTONDOWN,0x00A4)
XEVT(_T("WM_NCRBUTTONUP"),WM_NCRBUTTONUP,0x00A5)
XEVT(_T("WM_NCRBUTTONDBLCLK"),WM_NCRBUTTONDBLCLK,0x00A6)
XEVT(_T("WM_NCMBUTTONDOWN"),WM_NCMBUTTONDOWN,0x00A7)
XEVT(_T("WM_NCMBUTTONUP"),WM_NCMBUTTONUP,0x00A8)
XEVT(_T("WM_NCMBUTTONDBLCLK"),WM_NCMBUTTONDBLCLK,0x00A9)

XEVT(_T("WM_NCXBUTTONDOWN"),WM_NCXBUTTONDOWN,0x00AB)
XEVT(_T("WM_NCXBUTTONUP"),WM_NCXBUTTONUP,0x00AC)
XEVT(_T("WM_NCXBUTTONDBLCLK"),WM_NCXBUTTONDBLCLK,0x00AD)
XEVT(_T("WM_INPUT"),WM_INPUT,0x00FF)

XEVT(_T("WM_KEYFIRST"),WM_KEYFIRST,0x0100)
XEVT(_T("WM_KEYDOWN"),WM_KEYDOWN,0x0100)
XEVT(_T("WM_KEYUP"),WM_KEYUP,0x0101)
XEVT(_T("WM_CHAR"),WM_CHAR,0x0102)
XEVT(_T("WM_DEADCHAR"),WM_DEADCHAR,0x0103)
XEVT(_T("WM_SYSKEYDOWN"),WM_SYSKEYDOWN,0x0104)
XEVT(_T("WM_SYSKEYUP"),WM_SYSKEYUP,0x0105)
XEVT(_T("WM_SYSCHAR"),WM_SYSCHAR,0x0106)
XEVT(_T("WM_SYSDEADCHAR"),WM_SYSDEADCHAR,0x0107)

XEVT(_T("WM_UNICHAR"),WM_UNICHAR,0x0109)
XEVT(_T("WM_KEYLAST"),WM_KEYLAST,0x0109)
XEVT(_T("UNICODE_NOCHAR"),UNICODE_NOCHAR,0xFFFF)


XEVT(_T("WM_IME_STARTCOMPOSITION"),WM_IME_STARTCOMPOSITION,0x010D)
XEVT(_T("WM_IME_ENDCOMPOSITION"),WM_IME_ENDCOMPOSITION,0x010E)
XEVT(_T("WM_IME_COMPOSITION"),WM_IME_COMPOSITION,0x010F)
XEVT(_T("WM_IME_KEYLAST"),WM_IME_KEYLAST,0x010F)


XEVT(_T("WM_INITDIALOG"),WM_INITDIALOG,0x0110)
XEVT(_T("WM_COMMAND"),WM_COMMAND,0x0111)
XEVT(_T("WM_SYSCOMMAND"),WM_SYSCOMMAND,0x0112)
XEVT(_T("WM_TIMER"),WM_TIMER,0x0113)
XEVT(_T("WM_HSCROLL"),WM_HSCROLL,0x0114)
XEVT(_T("WM_VSCROLL"),WM_VSCROLL,0x0115)
XEVT(_T("WM_INITMENU"),WM_INITMENU,0x0116)
XEVT(_T("WM_INITMENUPOPUP"),WM_INITMENUPOPUP,0x0117)
XEVT(_T("WM_MENUSELECT"),WM_MENUSELECT,0x011F)
XEVT(_T("WM_MENUCHAR"),WM_MENUCHAR,0x0120)
XEVT(_T("WM_ENTERIDLE"),WM_ENTERIDLE,0x0121)

XEVT(_T("WM_MENURBUTTONUP"),WM_MENURBUTTONUP,0x0122)
XEVT(_T("WM_MENUDRAG"),WM_MENUDRAG,0x0123)
XEVT(_T("WM_MENUGETOBJECT"),WM_MENUGETOBJECT,0x0124)
XEVT(_T("WM_UNINITMENUPOPUP"),WM_UNINITMENUPOPUP,0x0125)
XEVT(_T("WM_MENUCOMMAND"),WM_MENUCOMMAND,0x0126)

XEVT(_T("WM_CHANGEUISTATE"),WM_CHANGEUISTATE,0x0127)
XEVT(_T("WM_UPDATEUISTATE"),WM_UPDATEUISTATE,0x0128)
XEVT(_T("WM_QUERYUISTATE"),WM_QUERYUISTATE,0x0129)


XEVT(_T("WM_CTLCOLORMSGBOX"),WM_CTLCOLORMSGBOX,0x0132)
XEVT(_T("WM_CTLCOLOREDIT"),WM_CTLCOLOREDIT,0x0133)
XEVT(_T("WM_CTLCOLORLISTBOX"),WM_CTLCOLORLISTBOX,0x0134)
XEVT(_T("WM_CTLCOLORBTN"),WM_CTLCOLORBTN,0x0135)
XEVT(_T("WM_CTLCOLORDLG"),WM_CTLCOLORDLG,0x0136)
XEVT(_T("WM_CTLCOLORSCROLLBAR"),WM_CTLCOLORSCROLLBAR,0x0137)
XEVT(_T("WM_CTLCOLORSTATIC"),WM_CTLCOLORSTATIC,0x0138)
XEVT(_T("MN_GETHMENU"),MN_GETHMENU,0x01E1)

XEVT(_T("WM_MOUSEFIRST"),WM_MOUSEFIRST,0x0200)
XEVT(_T("WM_MOUSEMOVE"),WM_MOUSEMOVE,0x0200)
XEVT(_T("WM_LBUTTONDOWN"),WM_LBUTTONDOWN,0x0201)
XEVT(_T("WM_LBUTTONUP"),WM_LBUTTONUP,0x0202)
XEVT(_T("WM_LBUTTONDBLCLK"),WM_LBUTTONDBLCLK,0x0203)
XEVT(_T("WM_RBUTTONDOWN"),WM_RBUTTONDOWN,0x0204)
XEVT(_T("WM_RBUTTONUP"),WM_RBUTTONUP,0x0205)
XEVT(_T("WM_RBUTTONDBLCLK"),WM_RBUTTONDBLCLK,0x0206)
XEVT(_T("WM_MBUTTONDOWN"),WM_MBUTTONDOWN,0x0207)
XEVT(_T("WM_MBUTTONUP"),WM_MBUTTONUP,0x0208)
XEVT(_T("WM_MBUTTONDBLCLK"),WM_MBUTTONDBLCLK,0x0209)
XEVT(_T("WM_MOUSEWHEEL"),WM_MOUSEWHEEL,0x020A)
XEVT(_T("WM_XBUTTONDOWN"),WM_XBUTTONDOWN,0x020B)
XEVT(_T("WM_XBUTTONUP"),WM_XBUTTONUP,0x020C)
XEVT(_T("WM_XBUTTONDBLCLK"),WM_XBUTTONDBLCLK,0x020D)
XEVT(_T("WM_MOUSELAST"),WM_MOUSELAST,0x020D)




XEVT(_T("WM_PARENTNOTIFY"),WM_PARENTNOTIFY,0x0210)
XEVT(_T("WM_ENTERMENULOOP"),WM_ENTERMENULOOP,0x0211)
XEVT(_T("WM_EXITMENULOOP"),WM_EXITMENULOOP,0x0212)


XEVT(_T("WM_NEXTMENU"),WM_NEXTMENU,0x0213)
XEVT(_T("WM_SIZING"),WM_SIZING,0x0214)
XEVT(_T("WM_CAPTURECHANGED"),WM_CAPTURECHANGED,0x0215)
XEVT(_T("WM_MOVING"),WM_MOVING,0x0216)
XEVT(_T("WM_POWERBROADCAST"),WM_POWERBROADCAST,0x0218)
XEVT(_T("WM_DEVICECHANGE"),WM_DEVICECHANGE,0x0219)


XEVT(_T("WM_MDICREATE"),WM_MDICREATE,0x0220)
XEVT(_T("WM_MDIDESTROY"),WM_MDIDESTROY,0x0221)
XEVT(_T("WM_MDIACTIVATE"),WM_MDIACTIVATE,0x0222)
XEVT(_T("WM_MDIRESTORE"),WM_MDIRESTORE,0x0223)
XEVT(_T("WM_MDINEXT"),WM_MDINEXT,0x0224)
XEVT(_T("WM_MDIMAXIMIZE"),WM_MDIMAXIMIZE,0x0225)
XEVT(_T("WM_MDITILE"),WM_MDITILE,0x0226)
XEVT(_T("WM_MDICASCADE"),WM_MDICASCADE,0x0227)
XEVT(_T("WM_MDIICONARRANGE"),WM_MDIICONARRANGE,0x0228)
XEVT(_T("WM_MDIGETACTIVE"),WM_MDIGETACTIVE,0x0229)


XEVT(_T("WM_MDISETMENU"),WM_MDISETMENU,0x0230)
XEVT(_T("WM_ENTERSIZEMOVE"),WM_ENTERSIZEMOVE,0x0231)
XEVT(_T("WM_EXITSIZEMOVE"),WM_EXITSIZEMOVE,0x0232)
XEVT(_T("WM_DROPFILES"),WM_DROPFILES,0x0233)
XEVT(_T("WM_MDIREFRESHMENU"),WM_MDIREFRESHMENU,0x0234)



XEVT(_T("WM_IME_SETCONTEXT"),WM_IME_SETCONTEXT,0x0281)
XEVT(_T("WM_IME_NOTIFY"),WM_IME_NOTIFY,0x0282)
XEVT(_T("WM_IME_CONTROL"),WM_IME_CONTROL,0x0283)
XEVT(_T("WM_IME_COMPOSITIONFULL"),WM_IME_COMPOSITIONFULL,0x0284)
XEVT(_T("WM_IME_SELECT"),WM_IME_SELECT,0x0285)
XEVT(_T("WM_IME_CHAR"),WM_IME_CHAR,0x0286)

XEVT(_T("WM_IME_REQUEST"),WM_IME_REQUEST,0x0288)

XEVT(_T("WM_IME_KEYDOWN"),WM_IME_KEYDOWN,0x0290)
XEVT(_T("WM_IME_KEYUP"),WM_IME_KEYUP,0x0291)


XEVT(_T("WM_MOUSEHOVER"),WM_MOUSEHOVER,0x02A1)
XEVT(_T("WM_MOUSELEAVE"),WM_MOUSELEAVE,0x02A3)

XEVT(_T("WM_NCMOUSEHOVER"),WM_NCMOUSEHOVER,0x02A0)
XEVT(_T("WM_NCMOUSELEAVE"),WM_NCMOUSELEAVE,0x02A2)

XEVT(_T("WM_WTSSESSION_CHANGE"),WM_WTSSESSION_CHANGE,0x02B1)

XEVT(_T("WM_TABLET_FIRST"),WM_TABLET_FIRST,0x02c0)
XEVT(_T("WM_TABLET_LAST"),WM_TABLET_LAST,0x02df)

XEVT(_T("WM_CUT"),WM_CUT,0x0300)
XEVT(_T("WM_COPY"),WM_COPY,0x0301)
XEVT(_T("WM_PASTE"),WM_PASTE,0x0302)
XEVT(_T("WM_CLEAR"),WM_CLEAR,0x0303)
XEVT(_T("WM_UNDO"),WM_UNDO,0x0304)
XEVT(_T("WM_RENDERFORMAT"),WM_RENDERFORMAT,0x0305)
XEVT(_T("WM_RENDERALLFORMATS"),WM_RENDERALLFORMATS,0x0306)
XEVT(_T("WM_DESTROYCLIPBOARD"),WM_DESTROYCLIPBOARD,0x0307)
XEVT(_T("WM_DRAWCLIPBOARD"),WM_DRAWCLIPBOARD,0x0308)
XEVT(_T("WM_PAINTCLIPBOARD"),WM_PAINTCLIPBOARD,0x0309)
XEVT(_T("WM_VSCROLLCLIPBOARD"),WM_VSCROLLCLIPBOARD,0x030A)
XEVT(_T("WM_SIZECLIPBOARD"),WM_SIZECLIPBOARD,0x030B)
XEVT(_T("WM_ASKCBFORMATNAME"),WM_ASKCBFORMATNAME,0x030C)
XEVT(_T("WM_CHANGECBCHAIN"),WM_CHANGECBCHAIN,0x030D)
XEVT(_T("WM_HSCROLLCLIPBOARD"),WM_HSCROLLCLIPBOARD,0x030E)
XEVT(_T("WM_QUERYNEWPALETTE"),WM_QUERYNEWPALETTE,0x030F)
XEVT(_T("WM_PALETTEISCHANGING"),WM_PALETTEISCHANGING,0x0310)
XEVT(_T("WM_PALETTECHANGED"),WM_PALETTECHANGED,0x0311)
XEVT(_T("WM_HOTKEY"),WM_HOTKEY,0x0312)


XEVT(_T("WM_PRINT"),WM_PRINT,0x0317)
XEVT(_T("WM_PRINTCLIENT"),WM_PRINTCLIENT,0x0318)

XEVT(_T("WM_APPCOMMAND"),WM_APPCOMMAND,0x0319)

XEVT(_T("WM_THEMECHANGED"),WM_THEMECHANGED,0x031A)



XEVT(_T("WM_HANDHELDFIRST"),WM_HANDHELDFIRST,0x0358)
XEVT(_T("WM_HANDHELDLAST"),WM_HANDHELDLAST,0x035F)

XEVT(_T("WM_AFXFIRST"),WM_AFXFIRST,0x0360)
XEVT(_T("WM_AFXLAST"),WM_AFXLAST,0x037F)

XEVT(_T("WM_PENWINFIRST"),WM_PENWINFIRST,0x0380)
XEVT(_T("WM_PENWINLAST"),WM_PENWINLAST,0x038F)


XEVT(_T("WM_APP"),WM_APP,0x8000)
XEVT(_T("WM_USER"),WM_USER,0x0400)


XEVT(_T("NM_FIRST"),NM_FIRST,(0U-  0U))       // generic to all controls
XEVT(_T("NM_LAST"),NM_LAST,(0U- 99U))

//====== Generic WM_NOTIFY notification codes =================================
XEVT(_T("LVN_FIRST"),LVN_FIRST,(0U-100U))       // listview
XEVT(_T("LVN_LAST"),LVN_LAST,(0U-199U))

// Property sheet reserved      (0U-200U) -  (0U-299U) - see prsht.h
XEVT(_T("PSN_FIRST"),PSN_FIRST,(0U-200U))
XEVT(_T("PSN_LAST"),PSN_LAST,(0U-299U))

XEVT(_T("HDN_FIRST"),HDN_FIRST,(0U-300U))       // header
XEVT(_T("HDN_LAST"),HDN_LAST,(0U-399U))

XEVT(_T("TVN_FIRST"),TVN_FIRST,(0U-400U))       // treeview
XEVT(_T("TVN_LAST"),TVN_LAST,(0U-499U))

XEVT(_T("TTN_FIRST"),TTN_FIRST,(0U-520U))       // tooltips
XEVT(_T("TTN_LAST"),TTN_LAST,(0U-549U))

XEVT(_T("TCN_FIRST"),TCN_FIRST,(0U-550U))       // tab control
XEVT(_T("TCN_LAST"),TCN_LAST,(0U-580U))

// Shell reserved               (0U-580U) -  (0U-589U)

XEVT(_T("CDN_FIRST"),CDN_FIRST,(0U-601U))       // common dialog (new)
XEVT(_T("CDN_LAST"),CDN_LAST,(0U-699U))

XEVT(_T("TBN_FIRST"),TBN_FIRST,(0U-700U))       // toolbar
XEVT(_T("TBN_LAST"),TBN_LAST,(0U-720U))

XEVT(_T("UDN_FIRST"),UDN_FIRST,(0U-721))        // updown
XEVT(_T("UDN_LAST"),UDN_LAST,(0U-740))
#if (_WIN32_IE >= 0x0300)
XEVT(_T("MCN_FIRST"),MCN_FIRST,(0U-750U))       // monthcal
XEVT(_T("MCN_LAST"),MCN_LAST,(0U-759U))

XEVT(_T("DTN_FIRST"),DTN_FIRST,(0U-760U))       // datetimepick
XEVT(_T("DTN_LAST"),DTN_LAST,(0U-799U))

XEVT(_T("CBEN_FIRST"),CBEN_FIRST,(0U-800U))       // combo box ex
XEVT(_T("CBEN_LAST"),CBEN_LAST,(0U-830U))

XEVT(_T("RBN_FIRST"),RBN_FIRST,(0U-831U))       // rebar
XEVT(_T("RBN_LAST"),RBN_LAST,(0U-859U))
#endif

#if (_WIN32_IE >= 0x0400)
XEVT(_T("IPN_FIRST"),IPN_FIRST,(0U-860U))       // internet address
XEVT(_T("IPN_LAST"),IPN_LAST,(0U-879U))       // internet address

XEVT(_T("SBN_FIRST"),SBN_FIRST,(0U-880U))       // status bar
XEVT(_T("SBN_LAST"),SBN_LAST,(0U-899U))

XEVT(_T("PGN_FIRST"),PGN_FIRST,(0U-900U))       // Pager Control
XEVT(_T("PGN_LAST"),PGN_LAST,(0U-950U))

#endif

#if (_WIN32_IE >= 0x0500)
#ifndef WMN_FIRST
XEVT(_T("WMN_FIRST"),WMN_FIRST,(0U-1000U))
XEVT(_T("WMN_LAST"),WMN_LAST,(0U-1200U))
#endif
#endif

#if (_WIN32_WINNT >= 0x0501)
XEVT(_T("BCN_FIRST"),BCN_FIRST,(0U-1250U))
XEVT(_T("BCN_LAST"),BCN_LAST,(0U-1350U))
#endif

XEVT(_T("NM_OUTOFMEMORY"),NM_OUTOFMEMORY,(NM_FIRST-1))
XEVT(_T("NM_CLICK"),NM_CLICK,(NM_FIRST-2))    // uses NMCLICK struct
XEVT(_T("NM_DBLCLK"),NM_DBLCLK,(NM_FIRST-3))
XEVT(_T("NM_RETURN"),NM_RETURN,(NM_FIRST-4))
XEVT(_T("NM_RCLICK"),NM_RCLICK,(NM_FIRST-5))    // uses NMCLICK struct
XEVT(_T("NM_RDBLCLK"),NM_RDBLCLK,(NM_FIRST-6))
XEVT(_T("NM_SETFOCUS"),NM_SETFOCUS,(NM_FIRST-7))
XEVT(_T("NM_KILLFOCUS"),NM_KILLFOCUS,(NM_FIRST-8))
#if (_WIN32_IE >= 0x0300)
XEVT(_T("NM_CUSTOMDRAW"),NM_CUSTOMDRAW,(NM_FIRST-12))
XEVT(_T("NM_HOVER"),NM_HOVER,(NM_FIRST-13))
#endif
#if (_WIN32_IE >= 0x0400)
XEVT(_T("NM_NCHITTEST"),NM_NCHITTEST,(NM_FIRST-14))   // uses NMMOUSE struct
XEVT(_T("NM_KEYDOWN"),NM_KEYDOWN,(NM_FIRST-15))   // uses NMKEY struct
XEVT(_T("NM_RELEASEDCAPTURE"),NM_RELEASEDCAPTURE,(NM_FIRST-16))
XEVT(_T("NM_SETCURSOR"),NM_SETCURSOR,(NM_FIRST-17))   // uses NMMOUSE struct
XEVT(_T("NM_CHAR"),NM_CHAR,(NM_FIRST-18))   // uses NMCHAR struct
#endif
#if (_WIN32_IE >= 0x0401)
XEVT(_T("NM_TOOLTIPSCREATED"),NM_TOOLTIPSCREATED,(NM_FIRST-19))   // notify of when the tooltips window is create
#endif
#if (_WIN32_IE >= 0x0500)
XEVT(_T("NM_LDOWN"),NM_LDOWN,(NM_FIRST-20))
XEVT(_T("NM_RDOWN"),NM_RDOWN,(NM_FIRST-21))
XEVT(_T("NM_THEMECHANGED"),NM_THEMECHANGED,(NM_FIRST-22))
#endif

//Property Sheet Pages 
XEVT(_T("PSP_DEFAULT"),PSP_DEFAULT,0x00000000)
XEVT(_T("PSP_DLGINDIRECT"),PSP_DLGINDIRECT,0x00000001)
XEVT(_T("PSP_USEHICON"),PSP_USEHICON,0x00000002)
XEVT(_T("PSP_USEICONID"),PSP_USEICONID,0x00000004)
XEVT(_T("PSP_USETITLE"),PSP_USETITLE,0x00000008)
XEVT(_T("PSP_RTLREADING"),PSP_RTLREADING,0x00000010)

XEVT(_T("PSP_HASHELP"),PSP_HASHELP,0x00000020)
XEVT(_T("PSP_USEREFPARENT"),PSP_USEREFPARENT,0x00000040)
XEVT(_T("PSP_USECALLBACK"),PSP_USECALLBACK,0x00000080)
XEVT(_T("PSP_PREMATURE"),PSP_PREMATURE,0x00000400)

#if (_WIN32_IE >= 0x0400)
//----- New flags for wizard97 --------------
XEVT(_T("PSP_HIDEHEADER"),PSP_HIDEHEADER,0x00000800)
XEVT(_T("PSP_USEHEADERTITLE"),PSP_USEHEADERTITLE,0x00001000)
XEVT(_T("PSP_USEHEADERSUBTITLE"),PSP_USEHEADERSUBTITLE,0x00002000)
//-------------------------------------------
#endif
#if (_WIN32_WINNT >= 0x0501) || ISOLATION_AWARE_ENABLED
XEVT(_T("PSP_USEFUSIONCONTEXT"),PSP_USEFUSIONCONTEXT,0x00004000)
#endif

//====== HEADER CONTROL =======================================================
XEVT(_T("HDN_ITEMCHANGINGA"),HDN_ITEMCHANGINGA,(HDN_FIRST-0))
XEVT(_T("HDN_ITEMCHANGINGW"),HDN_ITEMCHANGINGW,(HDN_FIRST-20))
XEVT(_T("HDN_ITEMCHANGEDA"),HDN_ITEMCHANGEDA,(HDN_FIRST-1))
XEVT(_T("HDN_ITEMCHANGEDW"),HDN_ITEMCHANGEDW,(HDN_FIRST-21))
XEVT(_T("HDN_ITEMCLICKA"),HDN_ITEMCLICKA,(HDN_FIRST-2))
XEVT(_T("HDN_ITEMCLICKW"),HDN_ITEMCLICKW,(HDN_FIRST-22))
XEVT(_T("HDN_ITEMDBLCLICKA"),HDN_ITEMDBLCLICKA,(HDN_FIRST-3))
XEVT(_T("HDN_ITEMDBLCLICKW"),HDN_ITEMDBLCLICKW,(HDN_FIRST-23))
XEVT(_T("HDN_DIVIDERDBLCLICKA"),HDN_DIVIDERDBLCLICKA,(HDN_FIRST-5))
XEVT(_T("HDN_DIVIDERDBLCLICKW"),HDN_DIVIDERDBLCLICKW,(HDN_FIRST-25))
XEVT(_T("HDN_BEGINTRACKA"),HDN_BEGINTRACKA,(HDN_FIRST-6))
XEVT(_T("HDN_BEGINTRACKW"),HDN_BEGINTRACKW,(HDN_FIRST-26))
XEVT(_T("HDN_ENDTRACKA"),HDN_ENDTRACKA,(HDN_FIRST-7))
XEVT(_T("HDN_ENDTRACKW"),HDN_ENDTRACKW,(HDN_FIRST-27))
XEVT(_T("HDN_TRACKA"),HDN_TRACKA,(HDN_FIRST-8))
XEVT(_T("HDN_TRACKW"),HDN_TRACKW,(HDN_FIRST-28))
#if (_WIN32_IE >= 0x0300)
XEVT(_T("HDN_GETDISPINFOA"),HDN_GETDISPINFOA,(HDN_FIRST-9))
XEVT(_T("HDN_GETDISPINFOW"),HDN_GETDISPINFOW,(HDN_FIRST-29))
XEVT(_T("HDN_BEGINDRAG"),HDN_BEGINDRAG,(HDN_FIRST-10))
XEVT(_T("HDN_ENDDRAG"),HDN_ENDDRAG,(HDN_FIRST-11))
#endif
#if (_WIN32_IE >= 0x0500)
XEVT(_T("HDN_FILTERCHANGE"),HDN_FILTERCHANGE,(HDN_FIRST-12))
XEVT(_T("HDN_FILTERBTNCLICK"),HDN_FILTERBTNCLICK,(HDN_FIRST-13))
#endif

#ifdef UNICODE
XEVT(_T("HDN_ITEMCHANGING"),HDN_ITEMCHANGING,HDN_ITEMCHANGINGW)
XEVT(_T("HDN_ITEMCHANGED"),HDN_ITEMCHANGED,HDN_ITEMCHANGEDW)
XEVT(_T("HDN_ITEMCLICK"),HDN_ITEMCLICK,HDN_ITEMCLICKW)
XEVT(_T("HDN_ITEMDBLCLICK"),HDN_ITEMDBLCLICK,HDN_ITEMDBLCLICKW)
XEVT(_T("HDN_DIVIDERDBLCLICK"),HDN_DIVIDERDBLCLICK,HDN_DIVIDERDBLCLICKW)
XEVT(_T("HDN_BEGINTRACK"),HDN_BEGINTRACK,HDN_BEGINTRACKW)
XEVT(_T("HDN_ENDTRACK"),HDN_ENDTRACK,HDN_ENDTRACKW)
XEVT(_T("HDN_TRACK"),HDN_TRACK,HDN_TRACKW)
#if (_WIN32_IE >= 0x0300)
XEVT(_T("HDN_GETDISPINFO"),HDN_GETDISPINFO,HDN_GETDISPINFOW)
#endif
#else
XEVT(_T("HDN_ITEMCHANGING"),HDN_ITEMCHANGING,HDN_ITEMCHANGINGA)
XEVT(_T("HDN_ITEMCHANGED"),HDN_ITEMCHANGED,HDN_ITEMCHANGEDA)
XEVT(_T("HDN_ITEMCLICK"),HDN_ITEMCLICK,HDN_ITEMCLICKA)
XEVT(_T("HDN_ITEMDBLCLICK"),HDN_ITEMDBLCLICK,HDN_ITEMDBLCLICKA)
XEVT(_T("HDN_DIVIDERDBLCLICK"),HDN_DIVIDERDBLCLICK,HDN_DIVIDERDBLCLICKA)
XEVT(_T("HDN_BEGINTRACK"),HDN_BEGINTRACK,HDN_BEGINTRACKA)
XEVT(_T("HDN_ENDTRACK"),HDN_ENDTRACK,HDN_ENDTRACKA)
XEVT(_T("HDN_TRACK"),HDN_TRACK,HDN_TRACKA)
#if (_WIN32_IE >= 0x0300)
XEVT(_T("HDN_GETDISPINFO"),HDN_GETDISPINFO,HDN_GETDISPINFOA)
#endif
#endif

//====== TOOLBAR CONTROL ======================================================
XEVT(_T("TBN_GETBUTTONINFOA"),TBN_GETBUTTONINFOA,(TBN_FIRST-0))
XEVT(_T("TBN_BEGINDRAG"),TBN_BEGINDRAG,(TBN_FIRST-1))
XEVT(_T("TBN_ENDDRAG"),TBN_ENDDRAG,(TBN_FIRST-2))
XEVT(_T("TBN_BEGINADJUST"),TBN_BEGINADJUST,(TBN_FIRST-3))
XEVT(_T("TBN_ENDADJUST"),TBN_ENDADJUST,(TBN_FIRST-4))
XEVT(_T("TBN_RESET"),TBN_RESET,(TBN_FIRST-5))
XEVT(_T("TBN_QUERYINSERT"),TBN_QUERYINSERT,(TBN_FIRST-6))
XEVT(_T("TBN_QUERYDELETE"),TBN_QUERYDELETE,(TBN_FIRST-7))
XEVT(_T("TBN_TOOLBARCHANGE"),TBN_TOOLBARCHANGE,(TBN_FIRST-8))
XEVT(_T("TBN_CUSTHELP"),TBN_CUSTHELP,(TBN_FIRST-9))
#if (_WIN32_IE >= 0x0300)
XEVT(_T("TBN_DROPDOWN"),TBN_DROPDOWN,(TBN_FIRST - 10))
#endif
#if (_WIN32_IE >= 0x0400)
XEVT(_T("TBN_GETOBJECT"),TBN_GETOBJECT,(TBN_FIRST - 12))
#endif

XEVT(_T("TBN_HOTITEMCHANGE"),TBN_HOTITEMCHANGE,(TBN_FIRST - 13))
XEVT(_T("TBN_DRAGOUT"),TBN_DRAGOUT,(TBN_FIRST - 14)) // this is sent when the user clicks down on a button then drags off the button
XEVT(_T("TBN_DELETINGBUTTON"),TBN_DELETINGBUTTON,(TBN_FIRST - 15)) // uses TBNOTIFY
XEVT(_T("TBN_GETDISPINFOA"),TBN_GETDISPINFOA,(TBN_FIRST - 16)) // This is sent when the  toolbar needs  some display information
XEVT(_T("TBN_GETDISPINFOW"),TBN_GETDISPINFOW,(TBN_FIRST - 17)) // This is sent when the  toolbar needs  some display information
XEVT(_T("TBN_GETINFOTIPA"),TBN_GETINFOTIPA,(TBN_FIRST - 18))
XEVT(_T("TBN_GETINFOTIPW"),TBN_GETINFOTIPW,(TBN_FIRST - 19))
XEVT(_T("TBN_GETBUTTONINFOW"),TBN_GETBUTTONINFOW,(TBN_FIRST - 20))
#if (_WIN32_IE >= 0x0500)
XEVT(_T("TBN_RESTORE"),TBN_RESTORE,(TBN_FIRST - 21))
XEVT(_T("TBN_SAVE"),TBN_SAVE,(TBN_FIRST - 22))
XEVT(_T("TBN_INITCUSTOMIZE"),TBN_INITCUSTOMIZE,(TBN_FIRST - 23))
#endif // (_WIN32_IE >= 0x0500)

#ifdef UNICODE
XEVT(_T("TBN_GETINFOTIP"),TBN_GETINFOTIP,TBN_GETINFOTIPW)
#else
XEVT(_T("TBN_GETINFOTIP"),TBN_GETINFOTIP,TBN_GETINFOTIPA)
#endif

#ifdef UNICODE
XEVT(_T("TBN_GETDISPINFO"),TBN_GETDISPINFO,TBN_GETDISPINFOW)
#else
XEVT(_T("TBN_GETDISPINFO"),TBN_GETDISPINFO,TBN_GETDISPINFOA)
#endif

#ifdef UNICODE
XEVT(_T("TBN_GETBUTTONINFO"),TBN_GETBUTTONINFO,TBN_GETBUTTONINFOW)
#else
XEVT(_T("TBN_GETBUTTONINFO"),TBN_GETBUTTONINFO,TBN_GETBUTTONINFOA)
#endif


//====== REBAR CONTROL ========================================================
XEVT(_T("RBN_HEIGHTCHANGE"),RBN_HEIGHTCHANGE,(RBN_FIRST - 0))

XEVT(_T("RBN_GETOBJECT"),RBN_GETOBJECT,(RBN_FIRST - 1))
XEVT(_T("RBN_LAYOUTCHANGED"),RBN_LAYOUTCHANGED,(RBN_FIRST - 2))
XEVT(_T("RBN_AUTOSIZE"),RBN_AUTOSIZE,(RBN_FIRST - 3))
XEVT(_T("RBN_BEGINDRAG"),RBN_BEGINDRAG,(RBN_FIRST - 4))
XEVT(_T("RBN_ENDDRAG"),RBN_ENDDRAG,(RBN_FIRST - 5))
XEVT(_T("RBN_DELETINGBAND"),RBN_DELETINGBAND,(RBN_FIRST - 6))     // Uses NMREBAR
XEVT(_T("RBN_DELETEDBAND"),RBN_DELETEDBAND,(RBN_FIRST - 7))     // Uses NMREBAR
XEVT(_T("RBN_CHILDSIZE"),RBN_CHILDSIZE,(RBN_FIRST - 8))

#if (_WIN32_IE >= 0x0500)
XEVT(_T("RBN_CHEVRONPUSHED"),RBN_CHEVRONPUSHED,(RBN_FIRST - 10))
#endif      // _WIN32_IE >= 0x0500


#if (_WIN32_IE >= 0x0500)
XEVT(_T("RBN_MINMAX"),RBN_MINMAX,(RBN_FIRST - 21))
#endif

#if (_WIN32_WINNT >= 0x0501)
XEVT(_T("RBN_AUTOBREAK"),RBN_AUTOBREAK,(RBN_FIRST - 22))
#endif


//====== TOOLTIPS CONTROL =====================================================
XEVT(_T("TTN_GETDISPINFOA"),TTN_GETDISPINFOA,(TTN_FIRST - 0))
XEVT(_T("TTN_GETDISPINFOW"),TTN_GETDISPINFOW,(TTN_FIRST - 10))
XEVT(_T("TTN_SHOW"),TTN_SHOW,(TTN_FIRST - 1))
XEVT(_T("TTN_POP"),TTN_POP,(TTN_FIRST - 2))
XEVT(_T("TTN_LINKCLICK"),TTN_LINKCLICK,(TTN_FIRST - 3))

#ifdef UNICODE
XEVT(_T("TTN_GETDISPINFO"),TTN_GETDISPINFO,TTN_GETDISPINFOW)
#else
XEVT(_T("TTN_GETDISPINFO"),TTN_GETDISPINFO,TTN_GETDISPINFOA)
#endif

XEVT(_T("TTN_NEEDTEXT"),TTN_NEEDTEXT,TTN_GETDISPINFO)
XEVT(_T("TTN_NEEDTEXTA"),TTN_NEEDTEXTA,TTN_GETDISPINFOA)
XEVT(_T("TTN_NEEDTEXTW"),TTN_NEEDTEXTW,TTN_GETDISPINFOW)

//====== STATUS BAR CONTROL ===================================================
/// status bar notifications
#if (_WIN32_IE >= 0x0400)
XEVT(_T("SBN_SIMPLEMODECHANGE"),SBN_SIMPLEMODECHANGE,(SBN_FIRST - 0))
#endif

//====== MENU HELP ============================================================

//====== TRACKBAR CONTROL =====================================================
//====== DRAG LIST CONTROL ====================================================
//====== UPDOWN CONTROL =======================================================
XEVT(_T("UDN_DELTAPOS"),UDN_DELTAPOS,(UDN_FIRST - 1))

//====== PROGRESS CONTROL =====================================================
//====== HOTKEY CONTROL =======================================================
//====== COMMON CONTROL STYLES ================================================
//====== LISTVIEW CONTROL =====================================================
XEVT(_T("LVN_ITEMCHANGING"),LVN_ITEMCHANGING,(LVN_FIRST-0))
XEVT(_T("LVN_ITEMCHANGED"),LVN_ITEMCHANGED,(LVN_FIRST-1))
XEVT(_T("LVN_INSERTITEM"),LVN_INSERTITEM,(LVN_FIRST-2))
XEVT(_T("LVN_DELETEITEM"),LVN_DELETEITEM,(LVN_FIRST-3))
XEVT(_T("LVN_DELETEALLITEMS"),LVN_DELETEALLITEMS,(LVN_FIRST-4))
XEVT(_T("LVN_BEGINLABELEDITA"),LVN_BEGINLABELEDITA,(LVN_FIRST-5))
XEVT(_T("LVN_BEGINLABELEDITW"),LVN_BEGINLABELEDITW,(LVN_FIRST-75))
XEVT(_T("LVN_ENDLABELEDITA"),LVN_ENDLABELEDITA,(LVN_FIRST-6))
XEVT(_T("LVN_ENDLABELEDITW"),LVN_ENDLABELEDITW,(LVN_FIRST-76))
XEVT(_T("LVN_COLUMNCLICK"),LVN_COLUMNCLICK,(LVN_FIRST-8))
XEVT(_T("LVN_BEGINDRAG"),LVN_BEGINDRAG,(LVN_FIRST-9))
XEVT(_T("LVN_BEGINRDRAG"),LVN_BEGINRDRAG,(LVN_FIRST-11))

#if (_WIN32_IE >= 0x0300)
XEVT(_T("LVN_ODCACHEHINT"),LVN_ODCACHEHINT,(LVN_FIRST-13))
XEVT(_T("LVN_ODFINDITEMA"),LVN_ODFINDITEMA,(LVN_FIRST-52))
XEVT(_T("LVN_ODFINDITEMW"),LVN_ODFINDITEMW,(LVN_FIRST-79))

XEVT(_T("LVN_ITEMACTIVATE"),LVN_ITEMACTIVATE,(LVN_FIRST-14))
XEVT(_T("LVN_ODSTATECHANGED"),LVN_ODSTATECHANGED,(LVN_FIRST-15))

#ifdef UNICODE
XEVT(_T("LVN_ODFINDITEM"),LVN_ODFINDITEM,LVN_ODFINDITEMW)
#else
XEVT(_T("LVN_ODFINDITEM"),LVN_ODFINDITEM,LVN_ODFINDITEMA)
#endif
#endif      // _WIN32_IE >= 0x0300


#if (_WIN32_IE >= 0x0400)
XEVT(_T("LVN_HOTTRACK"),LVN_HOTTRACK,(LVN_FIRST-21))
#endif

XEVT(_T("LVN_GETDISPINFOA"),LVN_GETDISPINFOA,(LVN_FIRST-50))
XEVT(_T("LVN_GETDISPINFOW"),LVN_GETDISPINFOW,(LVN_FIRST-77))
XEVT(_T("LVN_SETDISPINFOA"),LVN_SETDISPINFOA,(LVN_FIRST-51))
XEVT(_T("LVN_SETDISPINFOW"),LVN_SETDISPINFOW,(LVN_FIRST-78))

#ifdef UNICODE
XEVT(_T("LVN_BEGINLABELEDIT"),LVN_BEGINLABELEDIT,LVN_BEGINLABELEDITW)
XEVT(_T("LVN_ENDLABELEDIT"),LVN_ENDLABELEDIT,LVN_ENDLABELEDITW)
XEVT(_T("LVN_GETDISPINFO"),LVN_GETDISPINFO,LVN_GETDISPINFOW)
XEVT(_T("LVN_SETDISPINFO"),LVN_SETDISPINFO,LVN_SETDISPINFOW)
#else
XEVT(_T("LVN_BEGINLABELEDIT"),LVN_BEGINLABELEDIT,LVN_BEGINLABELEDITA)
XEVT(_T("LVN_ENDLABELEDIT"),LVN_ENDLABELEDIT,LVN_ENDLABELEDITA)
XEVT(_T("LVN_GETDISPINFO"),LVN_GETDISPINFO,LVN_GETDISPINFOA)
XEVT(_T("LVN_SETDISPINFO"),LVN_SETDISPINFO,LVN_SETDISPINFOA)
#endif


XEVT(_T("LVN_GETINFOTIPA"),LVN_GETINFOTIPA,(LVN_FIRST-57))
XEVT(_T("LVN_GETINFOTIPW"),LVN_GETINFOTIPW,(LVN_FIRST-58))

#ifdef UNICODE
XEVT(_T("LVN_GETINFOTIP"),LVN_GETINFOTIP,LVN_GETINFOTIPW)
#else
XEVT(_T("LVN_GETINFOTIP"),LVN_GETINFOTIP,LVN_GETINFOTIPA)
#endif

XEVT(_T("LVN_BEGINSCROLL"),LVN_BEGINSCROLL,(LVN_FIRST-80))          
XEVT(_T("LVN_ENDSCROLL"),LVN_ENDSCROLL,(LVN_FIRST-81))

//====== TREEVIEW CONTROL =====================================================
#define	TVN_RCLICK   TVN_FIRST-100
#define	TVN_ENDDRAG  TVN_FIRST-101
#define	TVN_LCLICK   TVN_FIRST-103
#define	TVN_CHECKBOXSEL   TVN_FIRST-104

XEVT(_T("TVN_SELCHANGINGA"),TVN_SELCHANGINGA,(TVN_FIRST-1))
XEVT(_T("TVN_SELCHANGINGW"),TVN_SELCHANGINGW,(TVN_FIRST-50))
XEVT(_T("TVN_SELCHANGEDA"),TVN_SELCHANGEDA,(TVN_FIRST-2))
XEVT(_T("TVN_SELCHANGEDW"),TVN_SELCHANGEDW,(TVN_FIRST-51))

XEVT(_T("TVN_GETDISPINFOA"),TVN_GETDISPINFOA,(TVN_FIRST-3))
XEVT(_T("TVN_GETDISPINFOW"),TVN_GETDISPINFOW,(TVN_FIRST-52))
XEVT(_T("TVN_SETDISPINFOA"),TVN_SETDISPINFOA,(TVN_FIRST-4))
XEVT(_T("TVN_SETDISPINFOW"),TVN_SETDISPINFOW,(TVN_FIRST-53))

XEVT(_T("TVN_ITEMEXPANDINGA"),TVN_ITEMEXPANDINGA,(TVN_FIRST-5))
XEVT(_T("TVN_ITEMEXPANDINGW"),TVN_ITEMEXPANDINGW,(TVN_FIRST-54))
XEVT(_T("TVN_ITEMEXPANDEDA"),TVN_ITEMEXPANDEDA,(TVN_FIRST-6))
XEVT(_T("TVN_ITEMEXPANDEDW"),TVN_ITEMEXPANDEDW,(TVN_FIRST-55))
XEVT(_T("TVN_BEGINDRAGA"),TVN_BEGINDRAGA,(TVN_FIRST-7))
XEVT(_T("TVN_BEGINDRAGW"),TVN_BEGINDRAGW,(TVN_FIRST-56))
XEVT(_T("TVN_BEGINRDRAGA"),TVN_BEGINRDRAGA,(TVN_FIRST-8))
XEVT(_T("TVN_BEGINRDRAGW"),TVN_BEGINRDRAGW,(TVN_FIRST-57))
XEVT(_T("TVN_DELETEITEMA"),TVN_DELETEITEMA,(TVN_FIRST-9))
XEVT(_T("TVN_DELETEITEMW"),TVN_DELETEITEMW,(TVN_FIRST-58))
XEVT(_T("TVN_BEGINLABELEDITA"),TVN_BEGINLABELEDITA,(TVN_FIRST-10))
XEVT(_T("TVN_BEGINLABELEDITW"),TVN_BEGINLABELEDITW,(TVN_FIRST-59))
XEVT(_T("TVN_ENDLABELEDITA"),TVN_ENDLABELEDITA,(TVN_FIRST-11))
XEVT(_T("TVN_ENDLABELEDITW"),TVN_ENDLABELEDITW,(TVN_FIRST-60))
XEVT(_T("TVN_KEYDOWN"),TVN_KEYDOWN,(TVN_FIRST-12))

XEVT(_T("TVN_RCLICK"),TVN_RCLICK,(TVN_FIRST-100))
XEVT(_T("TVN_ENDDRAG"),TVN_ENDDRAG,(TVN_FIRST-101))
XEVT(_T("TVN_LCLICK"),TVN_LCLICK,(TVN_FIRST-103))
XEVT(_T("TVN_CHECKBOXSEL"),TVN_CHECKBOXSEL,(TVN_FIRST-104))

#if (_WIN32_IE >= 0x0400)
XEVT(_T("TVN_GETINFOTIPA"),TVN_GETINFOTIPA,(TVN_FIRST-13))
XEVT(_T("TVN_GETINFOTIPW"),TVN_GETINFOTIPW,(TVN_FIRST-14))
XEVT(_T("TVN_SINGLEEXPAND"),TVN_SINGLEEXPAND,(TVN_FIRST-15))

#endif // 0x400

#ifdef UNICODE
XEVT(_T("TVN_SELCHANGING"),TVN_SELCHANGING,TVN_SELCHANGINGW)
XEVT(_T("TVN_SELCHANGED"),TVN_SELCHANGED,TVN_SELCHANGEDW)
XEVT(_T("TVN_GETDISPINFO"),TVN_GETDISPINFO,TVN_GETDISPINFOW)
XEVT(_T("TVN_SETDISPINFO"),TVN_SETDISPINFO,TVN_SETDISPINFOW)
XEVT(_T("TVN_ITEMEXPANDING"),TVN_ITEMEXPANDING,TVN_ITEMEXPANDINGW)
XEVT(_T("TVN_ITEMEXPANDED"),TVN_ITEMEXPANDED,TVN_ITEMEXPANDEDW)
XEVT(_T("TVN_BEGINDRAG"),TVN_BEGINDRAG,TVN_BEGINDRAGW)
XEVT(_T("TVN_BEGINRDRAG"),TVN_BEGINRDRAG,TVN_BEGINRDRAGW)
XEVT(_T("TVN_DELETEITEM"),TVN_DELETEITEM,TVN_DELETEITEMW)
XEVT(_T("TVN_BEGINLABELEDIT"),TVN_BEGINLABELEDIT,TVN_BEGINLABELEDITW)
XEVT(_T("TVN_ENDLABELEDIT"),TVN_ENDLABELEDIT,TVN_ENDLABELEDITW)
#else
XEVT(_T("TVN_SELCHANGING"),TVN_SELCHANGING,TVN_SELCHANGINGA)
XEVT(_T("TVN_SELCHANGED"),TVN_SELCHANGED,TVN_SELCHANGEDA)
XEVT(_T("TVN_GETDISPINFO"),TVN_GETDISPINFO,TVN_GETDISPINFOA)
XEVT(_T("TVN_SETDISPINFO"),TVN_SETDISPINFO,TVN_SETDISPINFOA)
XEVT(_T("TVN_ITEMEXPANDING"),TVN_ITEMEXPANDING,TVN_ITEMEXPANDINGA)
XEVT(_T("TVN_ITEMEXPANDED"),TVN_ITEMEXPANDED,TVN_ITEMEXPANDEDA)
XEVT(_T("TVN_BEGINDRAG"),TVN_BEGINDRAG,TVN_BEGINDRAGA)
XEVT(_T("TVN_BEGINRDRAG"),TVN_BEGINRDRAG,TVN_BEGINRDRAGA)
XEVT(_T("TVN_DELETEITEM"),TVN_DELETEITEM,TVN_DELETEITEMA)
XEVT(_T("TVN_BEGINLABELEDIT"),TVN_BEGINLABELEDIT,TVN_BEGINLABELEDITA)
XEVT(_T("TVN_ENDLABELEDIT"),TVN_ENDLABELEDIT,TVN_ENDLABELEDITA)
#endif

#ifdef UNICODE
XEVT(_T("TVN_GETINFOTIP"),TVN_GETINFOTIP,TVN_GETINFOTIPW)
#else
XEVT(_T("TVN_GETINFOTIP"),TVN_GETINFOTIP,TVN_GETINFOTIPA)
#endif

////////////////////  ComboBoxEx ////////////////////////////////
XEVT(_T("CBEN_GETDISPINFOW"),CBEN_GETDISPINFOW,(CBEN_FIRST - 7))
XEVT(_T("CBEN_GETDISPINFOA"),CBEN_GETDISPINFOA,(CBEN_FIRST - 0))
#ifdef UNICODE
XEVT(_T("CBEN_GETDISPINFO"),CBEN_GETDISPINFO,CBEN_GETDISPINFOW)
#else
XEVT(_T("CBEN_GETDISPINFO"),CBEN_GETDISPINFO,CBEN_GETDISPINFOA)
#endif

XEVT(_T("CBEN_INSERTITEM"),CBEN_INSERTITEM,(CBEN_FIRST - 1))
XEVT(_T("CBEN_DELETEITEM"),CBEN_DELETEITEM,(CBEN_FIRST - 2))
XEVT(_T("CBEN_BEGINEDIT"),CBEN_BEGINEDIT,(CBEN_FIRST - 4))
XEVT(_T("CBEN_ENDEDITA"),CBEN_ENDEDITA,(CBEN_FIRST - 5))
XEVT(_T("CBEN_ENDEDITW"),CBEN_ENDEDITW,(CBEN_FIRST - 6))

XEVT(_T("CBEN_DRAGBEGINA"),CBEN_DRAGBEGINA,(CBEN_FIRST - 8))
XEVT(_T("CBEN_DRAGBEGINW"),CBEN_DRAGBEGINW,(CBEN_FIRST - 9))

#ifdef UNICODE
XEVT(_T("CBEN_DRAGBEGIN"),CBEN_DRAGBEGIN,CBEN_DRAGBEGINW)
#else
XEVT(_T("CBEN_DRAGBEGIN"),CBEN_DRAGBEGIN,CBEN_DRAGBEGINA)
#endif
// lParam specifies why the endedit is happening
#ifdef UNICODE
XEVT(_T("CBEN_ENDEDIT"),CBEN_ENDEDIT,CBEN_ENDEDITW)
#else
XEVT(_T("CBEN_ENDEDIT"),CBEN_ENDEDIT,CBEN_ENDEDITA)
#endif

//====== TAB CONTROL ==========================================================
XEVT(_T("TCN_KEYDOWN"),TCN_KEYDOWN,(TCN_FIRST - 0))
XEVT(_T("TCN_SELCHANGE"),TCN_SELCHANGE,(TCN_FIRST - 1))
XEVT(_T("TCN_SELCHANGING"),TCN_SELCHANGING,(TCN_FIRST - 2))
#if (_WIN32_IE >= 0x0400)
XEVT(_T("TCN_GETOBJECT"),TCN_GETOBJECT,(TCN_FIRST - 3))
#endif      // _WIN32_IE >= 0x0400
#if (_WIN32_IE >= 0x0500)
XEVT(_T("TCN_FOCUSCHANGE"),TCN_FOCUSCHANGE,(TCN_FIRST - 4))
#endif      // _WIN32_IE >= 0x0500


//====== ANIMATE CONTROL ======================================================
XEVT(_T("ACN_START"),ACN_START,1)
XEVT(_T("ACN_STOP"),ACN_STOP,2)

//====== MONTHCAL CONTROL ======================================================
XEVT(_T("MCN_SELCHANGE"),MCN_SELCHANGE,(MCN_FIRST + 1))
XEVT(_T("MCN_GETDAYSTATE"),MCN_GETDAYSTATE,(MCN_FIRST + 3))
XEVT(_T("MCN_SELECT"),MCN_SELECT,(MCN_FIRST + 4))

//====== DATETIMEPICK CONTROL ==================================================
#ifdef UNICODE
XEVT(_T("DTN_WMKEYDOWN"),DTN_WMKEYDOWN,DTN_WMKEYDOWNW)
#else
XEVT(_T("DTN_WMKEYDOWN"),DTN_WMKEYDOWN,DTN_WMKEYDOWNA)
#endif


XEVT(_T("DTN_FORMATA"),DTN_FORMATA,(DTN_FIRST + 4)) 
XEVT(_T("DTN_FORMATW"),DTN_FORMATW,(DTN_FIRST + 17))

#ifdef UNICODE
XEVT(_T("DTN_FORMAT"),DTN_FORMAT,DTN_FORMATW)
#else
XEVT(_T("DTN_FORMAT"),DTN_FORMAT,DTN_FORMATA)
#endif


XEVT(_T("DTN_FORMATQUERYA"),DTN_FORMATQUERYA,(DTN_FIRST + 5))
XEVT(_T("DTN_FORMATQUERYW"),DTN_FORMATQUERYW,(DTN_FIRST + 18))

#ifdef UNICODE
XEVT(_T("DTN_FORMATQUERY"),DTN_FORMATQUERY,DTN_FORMATQUERYW)
#else
XEVT(_T("DTN_FORMATQUERY"),DTN_FORMATQUERY,DTN_FORMATQUERYA)
#endif

XEVT(_T("DTN_DROPDOWN"),DTN_DROPDOWN,(DTN_FIRST + 6)) // MonthCal has dropped down
XEVT(_T("DTN_CLOSEUP"),DTN_CLOSEUP,(DTN_FIRST + 7)) // MonthCal is popping up


//    IP Address edit control
XEVT(_T("IPN_FIELDCHANGED"),IPN_FIELDCHANGED,(IPN_FIRST - 0))

//  ====================== Pager Control =============================
XEVT(_T("PGN_CALCSIZE"),PGN_CALCSIZE,(PGN_FIRST-2))
XEVT(_T("PGN_HOTITEMCHANGE"),PGN_HOTITEMCHANGE,(PGN_FIRST-3))


// === Native Font Control ===
/// ====================== Button Control =============================
XEVT(_T("BN_CLICKED"),BN_CLICKED,0)
XEVT(_T("BN_PAINT"),BN_PAINT,1)
XEVT(_T("BN_HILITE"),BN_HILITE,2)
XEVT(_T("BN_UNHILITE"),BN_UNHILITE,3)
XEVT(_T("BN_DISABLE"),BN_DISABLE,4)
XEVT(_T("BN_DOUBLECLICKED"),BN_DOUBLECLICKED,5)
#if(WINVER >= 0x0400)
XEVT(_T("BN_PUSHED"),BN_PUSHED,BN_HILITE)
XEVT(_T("BN_UNPUSHED"),BN_UNPUSHED,BN_UNHILITE)
XEVT(_T("BN_DBLCLK"),BN_DBLCLK,BN_DOUBLECLICKED)
XEVT(_T("BN_SETFOCUS"),BN_SETFOCUS,6)
XEVT(_T("BN_KILLFOCUS"),BN_KILLFOCUS,7)
#endif /* WINVER >= 0x0400 */

/// ====================== Static Control =============================
XEVT(_T("STN_CLICKED"),STN_CLICKED,0)
XEVT(_T("STN_DBLCLK"),STN_DBLCLK,1)
XEVT(_T("STN_ENABLE"),STN_ENABLE,2)
XEVT(_T("STN_DISABLE"),STN_DISABLE,3)

/// ====================== Edit Control =============================
/*
 * Edit Control Notification Codes
 */
XEVT(_T("EN_SETFOCUS"),EN_SETFOCUS,0x0100)
XEVT(_T("EN_KILLFOCUS"),EN_KILLFOCUS,0x0200)
XEVT(_T("EN_CHANGE"),EN_CHANGE,0x0300)
XEVT(_T("EN_UPDATE"),EN_UPDATE,0x0400)
XEVT(_T("EN_ERRSPACE"),EN_ERRSPACE,0x0500)
XEVT(_T("EN_MAXTEXT"),EN_MAXTEXT,0x0501)
XEVT(_T("EN_HSCROLL"),EN_HSCROLL,0x0601)
XEVT(_T("EN_VSCROLL"),EN_VSCROLL,0x0602)

#if(_WIN32_WINNT >= 0x0500)
XEVT(_T("EN_ALIGN_LTR_EC"),EN_ALIGN_LTR_EC,0x0700)
XEVT(_T("EN_ALIGN_RTL_EC"),EN_ALIGN_RTL_EC,0x0701)
#endif /* _WIN32_WINNT >= 0x0500 */
/// ====================== Listbox Control =============================
XEVT(_T("LBN_ERRSPACE"),LBN_ERRSPACE,(-2))
XEVT(_T("LBN_SELCHANGE"),LBN_SELCHANGE,1)
XEVT(_T("LBN_DBLCLK"),LBN_DBLCLK,2)
XEVT(_T("LBN_SELCANCEL"),LBN_SELCANCEL,3)
XEVT(_T("LBN_SETFOCUS"),LBN_SETFOCUS,4)
XEVT(_T("LBN_KILLFOCUS"),LBN_KILLFOCUS,5)

/// ====================== Combobox Control =============================
XEVT(_T("CBN_ERRSPACE"),CBN_ERRSPACE,(-1))
XEVT(_T("CBN_SELCHANGE"),CBN_SELCHANGE,1)
XEVT(_T("CBN_DBLCLK"),CBN_DBLCLK,2)
XEVT(_T("CBN_SETFOCUS"),CBN_SETFOCUS,3)
XEVT(_T("CBN_KILLFOCUS"),CBN_KILLFOCUS,4)
XEVT(_T("CBN_EDITCHANGE"),CBN_EDITCHANGE,5)
XEVT(_T("CBN_EDITUPDATE"),CBN_EDITUPDATE,6)
XEVT(_T("CBN_DROPDOWN"),CBN_DROPDOWN,7)
XEVT(_T("CBN_CLOSEUP"),CBN_CLOSEUP,8)
XEVT(_T("CBN_SELENDOK"),CBN_SELENDOK,9)
XEVT(_T("CBN_SELENDCANCEL"),CBN_SELENDCANCEL,10)
/// ====================== Scrollbar Control ============================

//====== SysLink control =========================================
// === MUI APIs ===
//====== TrackMouseEvent  =====================================================
#ifndef WM_MOUSEHOVER
XEVT(_T("WM_MOUSEHOVER"),WM_MOUSEHOVER,0x02A1)
XEVT(_T("WM_MOUSELEAVE"),WM_MOUSELEAVE,0x02A3)
#endif
//====== Flat Scrollbar APIs=========================================

//OWNER
XEVT(_T("WM_XCOMMAND"),WM_XCOMMAND,	 (WM_USER + 0x01))
XEVT(_T("WM_FOCUSNEXT"),WM_FOCUSNEXT,(WM_USER + 0x02))
XEVT(_T("WM_FOCUSPREV"),WM_FOCUSPREV, (WM_USER + 0x03))
XEVT(_T("WM_PRESWITCHLAYER"),WM_PRESWITCHLAYER, (WM_USER + 0x04))
XEVT(_T("WM_SWITCHLAYERED"),WM_SWITCHLAYERED, (WM_USER + 0x05))
XEVT(_T("WM_READNOTE"),  WM_READNOTE, (WM_USER + 0x06))
XEVT(_T("WM_POSTDESTROYWINDOW"),  WM_POSTDESTROYWINDOW, (WM_USER + 0x07))

XEVT(_T("WM_BINDERNOTIFY"),  WM_BINDERNOTIFY, (WM_USER + 0x32))
XEVT(_T("WM_NOTIFYBINDER"),  WM_NOTIFYBINDER, (WM_USER + 0x33))


#define DWV_ITEMFOCUSCHANGED 0x0001
#define DWV_ROWFOCUSCHANGED  0x0002
#define DWV_GETFOCUS		 0x0003
#define DWV_LOSEFOCUS		 0x0004
#define DWV_ITEMCHANGED		 0x0005
#define DWV_ITEMCHANGING	 0x0006
#define DWV_ASKSTYLE		 0x0007
#define	DWV_DOUBLECLICKED	 0x0008
#define	DWV_CLICKED			 0x0009
#define	DWV_RANGLECLCIKED	 0x0010
#define	DWV_ZOOMIN			 0x0011
#define	DWV_ZOOMOUT			 0x0012
#define	DWV_SCROLLUP		 0x0013
#define	DWV_SCROLLDOWN		 0x0014
#define	DWV_SCROLLLEFT		 0x0015
#define	DWV_SCROLLRIGHT		 0x0016
#define	DWV_CHILDARGS		 0x0017
#define	DWV_CHILDCONTENT	 0x0018
#define	DWV_RCLICKED		 0x0019
#define	DWV_ITEMBEINGEDIT	 0x0020
#define DWV_KEYDOWN			 0x0021
#define DWV_ITEMERROR		 0x0022
#define DWV_ASKDATA			 0x0023
#define DWV_ROWFOCUSCHANGEING  0x0024
#define DWV_EDITORLOSEFOCUS  0x0025
#define DWV_EDITTEXTCHANGED  0x0026

//dataview
XEVT(_T("DWV_ITEMFOCUSCHANGED"),DWV_ITEMFOCUSCHANGED,0x0001)
XEVT(_T("DWV_ROWFOCUSCHANGED"),DWV_ROWFOCUSCHANGED,0x0002)
XEVT(_T("DWV_GETFOCUS"),DWV_GETFOCUS,0x0003)
XEVT(_T("DWV_LOSEFOCUS"),DWV_LOSEFOCUS,0x0004)
XEVT(_T("DWV_ITEMCHANGED"),DWV_ITEMCHANGED,0x0005)	
XEVT(_T("DWV_ITEMCHANGING"),DWV_ITEMCHANGING,0x0006)
XEVT(_T("DWV_ASKSTYLE"),DWV_ASKSTYLE,0x0007)
XEVT(_T("DWV_DOUBLECLICKED"),DWV_DOUBLECLICKED ,0x0008)
XEVT(_T("DWV_CLICKED"),DWV_CLICKED ,0x0009)
XEVT(_T("DWV_RANGLECLCIKED"),DWV_RANGLECLCIKED,	 0x0010)
XEVT(_T("DWV_ZOOMIN"),		DWV_ZOOMIN,	 0x0011)
XEVT(_T("DWV_ZOOMOUT"),		DWV_ZOOMOUT,	 0x0012)
XEVT(_T("DWV_SCROLLUP"),	DWV_SCROLLUP,	 0x0013)
XEVT(_T("DWV_SCROLLDOWN"),	DWV_SCROLLDOWN,	 0x0014)
XEVT(_T("DWV_SCROLLLEFT"),	DWV_SCROLLLEFT,	 0x0015)
XEVT(_T("DWV_SCROLLRIGHT"),	DWV_SCROLLRIGHT, 0x0016)
XEVT(_T("DWV_CHILDARGS"),	DWV_CHILDARGS,	 0x0017)
XEVT(_T("DWV_CHILDCONTENT"),DWV_CHILDCONTENT, 0x0018)
XEVT(_T("DWV_RCLICKED"),DWV_RCLICKED,	  0x0019)
XEVT(_T("DWV_ITEMBEINGEDIT"),DWV_ITEMBEINGEDIT,	  0x0020)
XEVT(_T("DWV_KEYDOWN"),DWV_KEYDOWN,	  0x0021)
XEVT(_T("DWV_ITEMERROR"),DWV_ITEMERROR,	  0x0022)
XEVT(_T("DWV_ASKDATA"),DWV_ASKDATA,	  0x0023)
XEVT(_T("DWV_ROWFOCUSCHANGEING"),DWV_ROWFOCUSCHANGEING,0x0024)
XEVT(_T("DWV_EDITORLOSEFOCUS"),DWV_EDITORLOSEFOCUS,0x0025)
XEVT(_T("DWV_EDITTEXTCHANGED"),DWV_EDITTEXTCHANGED,0x0026)

#define FLC_DOUBLECLICKED		0x0001
#define FLC_OBJECTSELECTED		0x0002
#define FLC_LINKSELECTED		0x0003
#define FLC_OBJECTWILLDELETED	0x0004
#define FLC_LINKWILLDELETED		0x0005
#define FLC_OBJECTADDED			0x0006
#define FLC_LINKADDED			0x0007

//flowchart
XEVT(_T("FLC_DOUBLECLICKED"),FLC_DOUBLECLICKED,0x0001)
XEVT(_T("FLC_OBJECTSELECTED"),FLC_OBJECTSELECTED,0x0002)
XEVT(_T("FLC_LINKSELECTED"),FLC_LINKSELECTED,0x0003)
XEVT(_T("FLC_OBJECTWILLDELETED"),FLC_OBJECTWILLDELETED,0x0004)
XEVT(_T("FLC_LINKWILLDELETED"),FLC_LINKWILLDELETED,0x0005)
XEVT(_T("FLC_OBJECTADDED"),FLC_OBJECTADDED,0x0006)
XEVT(_T("FLC_LINKADDED"),FLC_LINKADDED,0x0007)

#define LYSN_PRESELECTSHEET 0x0001
#define LYSN_SELECTEDSHEET  0x0002
#define LYSN_CLOSESHEET	0x0003

//layersheet
XEVT(_T("LYSN_PRESELECTSHEET"),LYSN_PRESELECTSHEET,0x0001);
XEVT(_T("LYSN_SELECTEDSHEET"),LYSN_SELECTEDSHEET,  0x0002);
XEVT(_T("LYSN_CLOSESHEET"),LYSN_CLOSESHEET,  0x0003);

//cell
#define CELL_SELECTCHANGED	 0x0201
#define CELL_ITEMCHANGED     0x0202
#define CELL_ROWDELETED		 0x0203
#define CELL_COLUMNDELETED	 0x0204
#define CELL_NEEDTIPTEXT	 0x0205
XEVT(_T("CELL_SELECTCHANGED"),CELL_SELECTCHANGED,0x0201);
XEVT(_T("CELL_ITEMCHANGED"),CELL_ITEMCHANGED,  0x0202);
XEVT(_T("CELL_ROWDELETED"),CELL_ROWDELETED,0x0203);
XEVT(_T("CELL_COLUMNDELETED"),CELL_COLUMNDELETED,  0x0204);
XEVT(_T("CELL_NEEDTIPTEXT"),CELL_NEEDTIPTEXT,  0x0205);

//zoomer
#define ZM_POSCHANGED	0x0001
XEVT(_T("ZM_POSCHANGED"),ZM_POSCHANGED,0x0001);

//html
#define HTC_OBJECTCLICKED  0x01
#define HTC_OBJECTRCLICKED 0x02
#define HTC_OBJECTDBCLICKED  0x03
XEVT(_T("HTC_OBJECTCLICKED"),HTC_OBJECTCLICKED,0x01);
XEVT(_T("HTC_OBJECTRCLICKED"),HTC_OBJECTRCLICKED,  0x02);
XEVT(_T("HTC_OBJECTDBCLICKED"),HTC_OBJECTDBCLICKED,  0x03);

//image
#define	IMG_LDBCLICK   WM_USER + 0x100
#define	IMG_MOUSELEAVE   WM_USER + 0x101
#define	IMG_LCLICK   WM_USER + 0x102
#define	IMG_LABEL   WM_USER + 0x103
XEVT(_T("IMG_LDBCLICK"),IMG_LDBCLICK,WM_USER + 0x100);
XEVT(_T("IMG_MOUSELEAVE"),IMG_MOUSELEAVE,  WM_USER + 0x101);
XEVT(_T("IMG_LCLICK"),IMG_LCLICK,WM_USER + 0x102);
XEVT(_T("IMG_LABEL"),IMG_LABEL,WM_USER + 0x103);

//·ÖÒ³
#define	PAGE_CLICK  WM_USER + 0x201
XEVT(_T("PAGE_CLICK"),PAGE_CLICK, WM_USER + 0x201);

/*
#define	PAGE_CLICK  WM_USER + 0x400 + 0x80
XEVT(_T("PAGE_CLICK"),PAGE_CLICK, WM_USER + 0x201);
#define	PAGE_CLICK  WM_USER + 0x201
XEVT(_T("PAGE_CLICK"),PAGE_CLICK, WM_USER + 0x201);
*/