XEVT(_T("window.NULL"),WM_NULL,0x0000)
XEVT(_T("window.CREATE"),WM_CREATE,0x0001)
XEVT(_T("window.DESTROY"),WM_DESTROY,0x0002)
XEVT(_T("window.MOVE"),WM_MOVE,0x0003)
XEVT(_T("window.SIZE"),WM_SIZE,0x0005)

XEVT(_T("window.ACTIVATE"),WM_ACTIVATE,0x0006)

XEVT(_T("window.SETFOCUS"),WM_SETFOCUS,0x0007)
XEVT(_T("window.KILLFOCUS"),WM_KILLFOCUS,0x0008)
XEVT(_T("window.ENABLE"),WM_ENABLE,0x000A)
XEVT(_T("window.SETREDRAW"),WM_SETREDRAW,0x000B)
XEVT(_T("window.SETTEXT"),WM_SETTEXT,0x000C)
XEVT(_T("window.GETTEXT"),WM_GETTEXT,0x000D)
XEVT(_T("window.GETTEXTLENGTH"),WM_GETTEXTLENGTH,0x000E)
XEVT(_T("window.PAINT"),WM_PAINT,0x000F)
XEVT(_T("window.CLOSE"),WM_CLOSE,0x0010)

XEVT(_T("window.QUERYENDSESSION"),WM_QUERYENDSESSION,0x0011)
XEVT(_T("window.QUERYOPEN"),WM_QUERYOPEN,0x0013)
XEVT(_T("window.ENDSESSION"),WM_ENDSESSION,0x0016)

XEVT(_T("window.QUIT"),WM_QUIT,0x0012)
XEVT(_T("window.ERASEBKGND"),WM_ERASEBKGND,0x0014)
XEVT(_T("window.SYSCOLORCHANGE"),WM_SYSCOLORCHANGE,0x0015)
XEVT(_T("window.SHOWWINDOW"),WM_SHOWWINDOW,0x0018)
XEVT(_T("window.WININICHANGE"),WM_WININICHANGE,0x001A)

XEVT(_T("window.SETTINGCHANGE"),WM_SETTINGCHANGE,WM_WININICHANGE)



XEVT(_T("window.DEVMODECHANGE"),WM_DEVMODECHANGE,0x001B)
XEVT(_T("window.ACTIVATEAPP"),WM_ACTIVATEAPP,0x001C)
XEVT(_T("window.FONTCHANGE"),WM_FONTCHANGE,0x001D)
XEVT(_T("window.TIMECHANGE"),WM_TIMECHANGE,0x001E)
XEVT(_T("window.CANCELMODE"),WM_CANCELMODE,0x001F)
XEVT(_T("window.SETCURSOR"),WM_SETCURSOR,0x0020)
XEVT(_T("window.MOUSEACTIVATE"),WM_MOUSEACTIVATE,0x0021)
XEVT(_T("window.CHILDACTIVATE"),WM_CHILDACTIVATE,0x0022)
XEVT(_T("window.QUEUESYNC"),WM_QUEUESYNC,0x0023)

XEVT(_T("window.GETMINMAXINFO"),WM_GETMINMAXINFO,0x0024)

XEVT(_T("window.PAINTICON"),WM_PAINTICON,0x0026)
XEVT(_T("window.ICONERASEBKGND"),WM_ICONERASEBKGND,0x0027)
XEVT(_T("window.NEXTDLGCTL"),WM_NEXTDLGCTL,0x0028)
XEVT(_T("window.SPOOLERSTATUS"),WM_SPOOLERSTATUS,0x002A)
XEVT(_T("window.DRAWITEM"),WM_DRAWITEM,0x002B)
XEVT(_T("window.MEASUREITEM"),WM_MEASUREITEM,0x002C)
XEVT(_T("window.DELETEITEM"),WM_DELETEITEM,0x002D)
XEVT(_T("window.VKEYTOITEM"),WM_VKEYTOITEM,0x002E)
XEVT(_T("window.CHARTOITEM"),WM_CHARTOITEM,0x002F)
XEVT(_T("window.SETFONT"),WM_SETFONT,0x0030)
XEVT(_T("window.GETFONT"),WM_GETFONT,0x0031)
XEVT(_T("window.SETHOTKEY"),WM_SETHOTKEY,0x0032)
XEVT(_T("window.GETHOTKEY"),WM_GETHOTKEY,0x0033)
XEVT(_T("window.QUERYDRAGICON"),WM_QUERYDRAGICON,0x0037)
XEVT(_T("window.COMPAREITEM"),WM_COMPAREITEM,0x0039)

XEVT(_T("window.GETOBJECT"),WM_GETOBJECT,0x003D)

XEVT(_T("window.COMPACTING"),WM_COMPACTING,0x0041)
XEVT(_T("window.COMMNOTIFY"),WM_COMMNOTIFY,0x0044)  
XEVT(_T("window.WINDOWPOSCHANGING"),WM_WINDOWPOSCHANGING,0x0046)
XEVT(_T("window.WINDOWPOSCHANGED"),WM_WINDOWPOSCHANGED,0x0047)

XEVT(_T("window.POWER"),WM_POWER,0x0048)

XEVT(_T("window.COPYDATA"),WM_COPYDATA,0x004A)
XEVT(_T("window.CANCELJOURNAL"),WM_CANCELJOURNAL,0x004B)

XEVT(_T("window.NOTIFY"),WM_NOTIFY,0x004E)
XEVT(_T("window.INPUTLANGCHANGEREQUEST"),WM_INPUTLANGCHANGEREQUEST,0x0050)
XEVT(_T("window.INPUTLANGCHANGE"),WM_INPUTLANGCHANGE,0x0051)
XEVT(_T("window.TCARD"),WM_TCARD,0x0052)
XEVT(_T("window.HELP"),WM_HELP,0x0053)
XEVT(_T("window.USERCHANGED"),WM_USERCHANGED,0x0054)
XEVT(_T("window.NOTIFYFORMAT"),WM_NOTIFYFORMAT,0x0055)

XEVT(_T("window.CONTEXTMENU"),WM_CONTEXTMENU,0x007B)
XEVT(_T("window.STYLECHANGING"),WM_STYLECHANGING,0x007C)
XEVT(_T("window.STYLECHANGED"),WM_STYLECHANGED,0x007D)
XEVT(_T("window.DISPLAYCHANGE"),WM_DISPLAYCHANGE,0x007E)
XEVT(_T("window.GETICON"),WM_GETICON,0x007F)
XEVT(_T("window.SETICON"),WM_SETICON,0x0080)

XEVT(_T("window.NCCREATE"),WM_NCCREATE,0x0081)
XEVT(_T("window.NCDESTROY"),WM_NCDESTROY,0x0082)
XEVT(_T("window.NCCALCSIZE"),WM_NCCALCSIZE,0x0083)
XEVT(_T("window.NCHITTEST"),WM_NCHITTEST,0x0084)
XEVT(_T("window.NCPAINT"),WM_NCPAINT,0x0085)
XEVT(_T("window.NCACTIVATE"),WM_NCACTIVATE,0x0086)
XEVT(_T("window.GETDLGCODE"),WM_GETDLGCODE,0x0087)

XEVT(_T("window.SYNCPAINT"),WM_SYNCPAINT,0x0088)

XEVT(_T("window.NCMOUSEMOVE"),WM_NCMOUSEMOVE,0x00A0)
XEVT(_T("window.NCLBUTTONDOWN"),WM_NCLBUTTONDOWN,0x00A1)
XEVT(_T("window.NCLBUTTONUP"),WM_NCLBUTTONUP,0x00A2)
XEVT(_T("window.NCLBUTTONDBLCLK"),WM_NCLBUTTONDBLCLK,0x00A3)
XEVT(_T("window.NCRBUTTONDOWN"),WM_NCRBUTTONDOWN,0x00A4)
XEVT(_T("window.NCRBUTTONUP"),WM_NCRBUTTONUP,0x00A5)
XEVT(_T("window.NCRBUTTONDBLCLK"),WM_NCRBUTTONDBLCLK,0x00A6)
XEVT(_T("window.NCMBUTTONDOWN"),WM_NCMBUTTONDOWN,0x00A7)
XEVT(_T("window.NCMBUTTONUP"),WM_NCMBUTTONUP,0x00A8)
XEVT(_T("window.NCMBUTTONDBLCLK"),WM_NCMBUTTONDBLCLK,0x00A9)

XEVT(_T("window.NCXBUTTONDOWN"),WM_NCXBUTTONDOWN,0x00AB)
XEVT(_T("window.NCXBUTTONUP"),WM_NCXBUTTONUP,0x00AC)
XEVT(_T("window.NCXBUTTONDBLCLK"),WM_NCXBUTTONDBLCLK,0x00AD)
XEVT(_T("window.INPUT"),WM_INPUT,0x00FF)

XEVT(_T("window.KEYFIRST"),WM_KEYFIRST,0x0100)
XEVT(_T("window.KEYDOWN"),WM_KEYDOWN,0x0100)
XEVT(_T("window.KEYUP"),WM_KEYUP,0x0101)
XEVT(_T("window.CHAR"),WM_CHAR,0x0102)
XEVT(_T("window.DEADCHAR"),WM_DEADCHAR,0x0103)
XEVT(_T("window.SYSKEYDOWN"),WM_SYSKEYDOWN,0x0104)
XEVT(_T("window.SYSKEYUP"),WM_SYSKEYUP,0x0105)
XEVT(_T("window.SYSCHAR"),WM_SYSCHAR,0x0106)
XEVT(_T("window.SYSDEADCHAR"),WM_SYSDEADCHAR,0x0107)

XEVT(_T("window.UNICHAR"),WM_UNICHAR,0x0109)
XEVT(_T("window.KEYLAST"),WM_KEYLAST,0x0109)
XEVT(_T("UNICODE_NOCHAR"),UNICODE_NOCHAR,0xFFFF)


XEVT(_T("window.IME_STARTCOMPOSITION"),WM_IME_STARTCOMPOSITION,0x010D)
XEVT(_T("window.IME_ENDCOMPOSITION"),WM_IME_ENDCOMPOSITION,0x010E)
XEVT(_T("window.IME_COMPOSITION"),WM_IME_COMPOSITION,0x010F)
XEVT(_T("window.IME_KEYLAST"),WM_IME_KEYLAST,0x010F)


XEVT(_T("window.INITDIALOG"),WM_INITDIALOG,0x0110)
XEVT(_T("window.COMMAND"),WM_COMMAND,0x0111)
XEVT(_T("window.SYSCOMMAND"),WM_SYSCOMMAND,0x0112)
XEVT(_T("window.TIMER"),WM_TIMER,0x0113)
XEVT(_T("window.HSCROLL"),WM_HSCROLL,0x0114)
XEVT(_T("window.VSCROLL"),WM_VSCROLL,0x0115)
XEVT(_T("window.INITMENU"),WM_INITMENU,0x0116)
XEVT(_T("window.INITMENUPOPUP"),WM_INITMENUPOPUP,0x0117)
XEVT(_T("window.MENUSELECT"),WM_MENUSELECT,0x011F)
XEVT(_T("window.MENUCHAR"),WM_MENUCHAR,0x0120)
XEVT(_T("window.ENTERIDLE"),WM_ENTERIDLE,0x0121)

XEVT(_T("window.MENURBUTTONUP"),WM_MENURBUTTONUP,0x0122)
XEVT(_T("window.MENUDRAG"),WM_MENUDRAG,0x0123)
XEVT(_T("window.MENUGETOBJECT"),WM_MENUGETOBJECT,0x0124)
XEVT(_T("window.UNINITMENUPOPUP"),WM_UNINITMENUPOPUP,0x0125)
XEVT(_T("window.MENUCOMMAND"),WM_MENUCOMMAND,0x0126)

XEVT(_T("window.CHANGEUISTATE"),WM_CHANGEUISTATE,0x0127)
XEVT(_T("window.UPDATEUISTATE"),WM_UPDATEUISTATE,0x0128)
XEVT(_T("window.QUERYUISTATE"),WM_QUERYUISTATE,0x0129)


XEVT(_T("window.CTLCOLORMSGBOX"),WM_CTLCOLORMSGBOX,0x0132)
XEVT(_T("window.CTLCOLOREDIT"),WM_CTLCOLOREDIT,0x0133)
XEVT(_T("window.CTLCOLORLISTBOX"),WM_CTLCOLORLISTBOX,0x0134)
XEVT(_T("window.CTLCOLORBTN"),WM_CTLCOLORBTN,0x0135)
XEVT(_T("window.CTLCOLORDLG"),WM_CTLCOLORDLG,0x0136)
XEVT(_T("window.CTLCOLORSCROLLBAR"),WM_CTLCOLORSCROLLBAR,0x0137)
XEVT(_T("window.CTLCOLORSTATIC"),WM_CTLCOLORSTATIC,0x0138)
XEVT(_T("MN_GETHMENU"),MN_GETHMENU,0x01E1)

XEVT(_T("window.MOUSEFIRST"),WM_MOUSEFIRST,0x0200)
XEVT(_T("window.MOUSEMOVE"),WM_MOUSEMOVE,0x0200)
XEVT(_T("window.LBUTTONDOWN"),WM_LBUTTONDOWN,0x0201)
XEVT(_T("window.LBUTTONUP"),WM_LBUTTONUP,0x0202)
XEVT(_T("window.LBUTTONDBLCLK"),WM_LBUTTONDBLCLK,0x0203)
XEVT(_T("window.RBUTTONDOWN"),WM_RBUTTONDOWN,0x0204)
XEVT(_T("window.RBUTTONUP"),WM_RBUTTONUP,0x0205)
XEVT(_T("window.RBUTTONDBLCLK"),WM_RBUTTONDBLCLK,0x0206)
XEVT(_T("window.MBUTTONDOWN"),WM_MBUTTONDOWN,0x0207)
XEVT(_T("window.MBUTTONUP"),WM_MBUTTONUP,0x0208)
XEVT(_T("window.MBUTTONDBLCLK"),WM_MBUTTONDBLCLK,0x0209)
XEVT(_T("window.MOUSEWHEEL"),WM_MOUSEWHEEL,0x020A)
XEVT(_T("window.XBUTTONDOWN"),WM_XBUTTONDOWN,0x020B)
XEVT(_T("window.XBUTTONUP"),WM_XBUTTONUP,0x020C)
XEVT(_T("window.XBUTTONDBLCLK"),WM_XBUTTONDBLCLK,0x020D)
XEVT(_T("window.MOUSELAST"),WM_MOUSELAST,0x020D)




XEVT(_T("window.PARENTNOTIFY"),WM_PARENTNOTIFY,0x0210)
XEVT(_T("window.ENTERMENULOOP"),WM_ENTERMENULOOP,0x0211)
XEVT(_T("window.EXITMENULOOP"),WM_EXITMENULOOP,0x0212)


XEVT(_T("window.NEXTMENU"),WM_NEXTMENU,0x0213)
XEVT(_T("window.SIZING"),WM_SIZING,0x0214)
XEVT(_T("window.CAPTURECHANGED"),WM_CAPTURECHANGED,0x0215)
XEVT(_T("window.MOVING"),WM_MOVING,0x0216)
XEVT(_T("window.POWERBROADCAST"),WM_POWERBROADCAST,0x0218)
XEVT(_T("window.DEVICECHANGE"),WM_DEVICECHANGE,0x0219)


XEVT(_T("window.MDICREATE"),WM_MDICREATE,0x0220)
XEVT(_T("window.MDIDESTROY"),WM_MDIDESTROY,0x0221)
XEVT(_T("window.MDIACTIVATE"),WM_MDIACTIVATE,0x0222)
XEVT(_T("window.MDIRESTORE"),WM_MDIRESTORE,0x0223)
XEVT(_T("window.MDINEXT"),WM_MDINEXT,0x0224)
XEVT(_T("window.MDIMAXIMIZE"),WM_MDIMAXIMIZE,0x0225)
XEVT(_T("window.MDITILE"),WM_MDITILE,0x0226)
XEVT(_T("window.MDICASCADE"),WM_MDICASCADE,0x0227)
XEVT(_T("window.MDIICONARRANGE"),WM_MDIICONARRANGE,0x0228)
XEVT(_T("window.MDIGETACTIVE"),WM_MDIGETACTIVE,0x0229)


XEVT(_T("window.MDISETMENU"),WM_MDISETMENU,0x0230)
XEVT(_T("window.ENTERSIZEMOVE"),WM_ENTERSIZEMOVE,0x0231)
XEVT(_T("window.EXITSIZEMOVE"),WM_EXITSIZEMOVE,0x0232)
XEVT(_T("window.DROPFILES"),WM_DROPFILES,0x0233)
XEVT(_T("window.MDIREFRESHMENU"),WM_MDIREFRESHMENU,0x0234)



XEVT(_T("window.IME_SETCONTEXT"),WM_IME_SETCONTEXT,0x0281)
XEVT(_T("window.IME_NOTIFY"),WM_IME_NOTIFY,0x0282)
XEVT(_T("window.IME_CONTROL"),WM_IME_CONTROL,0x0283)
XEVT(_T("window.IME_COMPOSITIONFULL"),WM_IME_COMPOSITIONFULL,0x0284)
XEVT(_T("window.IME_SELECT"),WM_IME_SELECT,0x0285)
XEVT(_T("window.IME_CHAR"),WM_IME_CHAR,0x0286)

XEVT(_T("window.IME_REQUEST"),WM_IME_REQUEST,0x0288)

XEVT(_T("window.IME_KEYDOWN"),WM_IME_KEYDOWN,0x0290)
XEVT(_T("window.IME_KEYUP"),WM_IME_KEYUP,0x0291)


XEVT(_T("window.MOUSEHOVER"),WM_MOUSEHOVER,0x02A1)
XEVT(_T("window.MOUSELEAVE"),WM_MOUSELEAVE,0x02A3)

XEVT(_T("window.NCMOUSEHOVER"),WM_NCMOUSEHOVER,0x02A0)
XEVT(_T("window.NCMOUSELEAVE"),WM_NCMOUSELEAVE,0x02A2)

XEVT(_T("window.WTSSESSION_CHANGE"),WM_WTSSESSION_CHANGE,0x02B1)

XEVT(_T("window.TABLET_FIRST"),WM_TABLET_FIRST,0x02c0)
XEVT(_T("window.TABLET_LAST"),WM_TABLET_LAST,0x02df)

XEVT(_T("window.CUT"),WM_CUT,0x0300)
XEVT(_T("window.COPY"),WM_COPY,0x0301)
XEVT(_T("window.PASTE"),WM_PASTE,0x0302)
XEVT(_T("window.CLEAR"),WM_CLEAR,0x0303)
XEVT(_T("window.UNDO"),WM_UNDO,0x0304)
XEVT(_T("window.RENDERFORMAT"),WM_RENDERFORMAT,0x0305)
XEVT(_T("window.RENDERALLFORMATS"),WM_RENDERALLFORMATS,0x0306)
XEVT(_T("window.DESTROYCLIPBOARD"),WM_DESTROYCLIPBOARD,0x0307)
XEVT(_T("window.DRAWCLIPBOARD"),WM_DRAWCLIPBOARD,0x0308)
XEVT(_T("window.PAINTCLIPBOARD"),WM_PAINTCLIPBOARD,0x0309)
XEVT(_T("window.VSCROLLCLIPBOARD"),WM_VSCROLLCLIPBOARD,0x030A)
XEVT(_T("window.SIZECLIPBOARD"),WM_SIZECLIPBOARD,0x030B)
XEVT(_T("window.ASKCBFORMATNAME"),WM_ASKCBFORMATNAME,0x030C)
XEVT(_T("window.CHANGECBCHAIN"),WM_CHANGECBCHAIN,0x030D)
XEVT(_T("window.HSCROLLCLIPBOARD"),WM_HSCROLLCLIPBOARD,0x030E)
XEVT(_T("window.QUERYNEWPALETTE"),WM_QUERYNEWPALETTE,0x030F)
XEVT(_T("window.PALETTEISCHANGING"),WM_PALETTEISCHANGING,0x0310)
XEVT(_T("window.PALETTECHANGED"),WM_PALETTECHANGED,0x0311)
XEVT(_T("window.HOTKEY"),WM_HOTKEY,0x0312)


XEVT(_T("window.PRINT"),WM_PRINT,0x0317)
XEVT(_T("window.PRINTCLIENT"),WM_PRINTCLIENT,0x0318)

XEVT(_T("window.APPCOMMAND"),WM_APPCOMMAND,0x0319)

XEVT(_T("window.THEMECHANGED"),WM_THEMECHANGED,0x031A)



XEVT(_T("window.HANDHELDFIRST"),WM_HANDHELDFIRST,0x0358)
XEVT(_T("window.HANDHELDLAST"),WM_HANDHELDLAST,0x035F)

XEVT(_T("window.AFXFIRST"),WM_AFXFIRST,0x0360)
XEVT(_T("window.AFXLAST"),WM_AFXLAST,0x037F)

XEVT(_T("window.PENWINFIRST"),WM_PENWINFIRST,0x0380)
XEVT(_T("window.PENWINLAST"),WM_PENWINLAST,0x038F)


XEVT(_T("window.APP"),WM_APP,0x8000)
XEVT(_T("window.USER"),WM_USER,0x0400)


XEVT(_T("control.FIRST"),NM_FIRST,(0U-  0U))       // generic to all controls
XEVT(_T("control.LAST"),NM_LAST,(0U- 99U))

//====== Generic WM_NOTIFY notification codes =================================
XEVT(_T("listview.FIRST"),LVN_FIRST,(0U-100U))       // listview
XEVT(_T("listview.LAST"),LVN_LAST,(0U-199U))

// Property sheet reserved      (0U-200U) -  (0U-299U) - see prsht.h
XEVT(_T("propsheet.FIRST"),PSN_FIRST,(0U-200U))
XEVT(_T("propsheet.LAST"),PSN_LAST,(0U-299U))

XEVT(_T("header.FIRST"),HDN_FIRST,(0U-300U))       // header
XEVT(_T("header.LAST"),HDN_LAST,(0U-399U))

XEVT(_T("treeview.FIRST"),TVN_FIRST,(0U-400U))       // treeview
XEVT(_T("treeview.LAST"),TVN_LAST,(0U-499U))

XEVT(_T("toolbar.FIRST"),TTN_FIRST,(0U-520U))       // tooltips
XEVT(_T("toolbar.LAST"),TTN_LAST,(0U-549U))

XEVT(_T("tab.FIRST"),TCN_FIRST,(0U-550U))       // tab control
XEVT(_T("tab.LAST"),TCN_LAST,(0U-580U))

// Shell reserved               (0U-580U) -  (0U-589U)

XEVT(_T("CDN_FIRST"),CDN_FIRST,(0U-601U))       // common dialog (new)
XEVT(_T("CDN_LAST"),CDN_LAST,(0U-699U))

XEVT(_T("TBN_FIRST"),TBN_FIRST,(0U-700U))       // toolbar
XEVT(_T("TBN_LAST"),TBN_LAST,(0U-720U))

XEVT(_T("UDN_FIRST"),UDN_FIRST,(0U-721))        // updown
XEVT(_T("UDN_LAST"),UDN_LAST,(0U-740))
#if (_WIN32_IE >= 0x0300)
XEVT(_T("MCN_FIRST"),MCN_FIRST,(0U-750U))       // monthcal
XEVT(_T("MCN_LAST"),MCN_LAST,(0U-759U))

XEVT(_T("DTN_FIRST"),DTN_FIRST,(0U-760U))       // datetimepick
XEVT(_T("DTN_LAST"),DTN_LAST,(0U-799U))

XEVT(_T("CBEN_FIRST"),CBEN_FIRST,(0U-800U))       // combo box ex
XEVT(_T("CBEN_LAST"),CBEN_LAST,(0U-830U))

XEVT(_T("RBN_FIRST"),RBN_FIRST,(0U-831U))       // rebar
XEVT(_T("RBN_LAST"),RBN_LAST,(0U-859U))
#endif

#if (_WIN32_IE >= 0x0400)
XEVT(_T("IPN_FIRST"),IPN_FIRST,(0U-860U))       // internet address
XEVT(_T("IPN_LAST"),IPN_LAST,(0U-879U))       // internet address

XEVT(_T("SBN_FIRST"),SBN_FIRST,(0U-880U))       // status bar
XEVT(_T("SBN_LAST"),SBN_LAST,(0U-899U))

XEVT(_T("PGN_FIRST"),PGN_FIRST,(0U-900U))       // Pager Control
XEVT(_T("PGN_LAST"),PGN_LAST,(0U-950U))

#endif

#if (_WIN32_IE >= 0x0500)
#ifndef WMN_FIRST
XEVT(_T("WMN_FIRST"),WMN_FIRST,(0U-1000U))
XEVT(_T("WMN_LAST"),WMN_LAST,(0U-1200U))
#endif
#endif

#if (_WIN32_WINNT >= 0x0501)
XEVT(_T("BCN_FIRST"),BCN_FIRST,(0U-1250U))
XEVT(_T("BCN_LAST"),BCN_LAST,(0U-1350U))
#endif

XEVT(_T("control.OUTOFMEMORY"),NM_OUTOFMEMORY,(NM_FIRST-1))
XEVT(_T("control.CLICK"),NM_CLICK,(NM_FIRST-2))    // uses NMCLICK struct
XEVT(_T("control.DBLCLK"),NM_DBLCLK,(NM_FIRST-3))
XEVT(_T("control.RETURN"),NM_RETURN,(NM_FIRST-4))
XEVT(_T("control.RCLICK"),NM_RCLICK,(NM_FIRST-5))    // uses NMCLICK struct
XEVT(_T("control.RDBLCLK"),NM_RDBLCLK,(NM_FIRST-6))
XEVT(_T("control.SETFOCUS"),NM_SETFOCUS,(NM_FIRST-7))
XEVT(_T("control.KILLFOCUS"),NM_KILLFOCUS,(NM_FIRST-8))
#if (_WIN32_IE >= 0x0300)
XEVT(_T("control.CUSTOMDRAW"),NM_CUSTOMDRAW,(NM_FIRST-12))
XEVT(_T("control.HOVER"),NM_HOVER,(NM_FIRST-13))
#endif
#if (_WIN32_IE >= 0x0400)
XEVT(_T("control.NCHITTEST"),NM_NCHITTEST,(NM_FIRST-14))   // uses NMMOUSE struct
XEVT(_T("control.KEYDOWN"),NM_KEYDOWN,(NM_FIRST-15))   // uses NMKEY struct
XEVT(_T("control.RELEASEDCAPTURE"),NM_RELEASEDCAPTURE,(NM_FIRST-16))
XEVT(_T("control.SETCURSOR"),NM_SETCURSOR,(NM_FIRST-17))   // uses NMMOUSE struct
XEVT(_T("control.CHAR"),NM_CHAR,(NM_FIRST-18))   // uses NMCHAR struct
#endif
#if (_WIN32_IE >= 0x0401)
XEVT(_T("control.TOOLTIPSCREATED"),NM_TOOLTIPSCREATED,(NM_FIRST-19))   // notify of when the tooltips window is create
#endif
#if (_WIN32_IE >= 0x0500)
XEVT(_T("control.LDOWN"),NM_LDOWN,(NM_FIRST-20))
XEVT(_T("control.RDOWN"),NM_RDOWN,(NM_FIRST-21))
XEVT(_T("control.THEMECHANGED"),NM_THEMECHANGED,(NM_FIRST-22))
#endif

//Property Sheet Pages 
XEVT(_T("PSP_DEFAULT"),PSP_DEFAULT,0x00000000)
XEVT(_T("PSP_DLGINDIRECT"),PSP_DLGINDIRECT,0x00000001)
XEVT(_T("PSP_USEHICON"),PSP_USEHICON,0x00000002)
XEVT(_T("PSP_USEICONID"),PSP_USEICONID,0x00000004)
XEVT(_T("PSP_USETITLE"),PSP_USETITLE,0x00000008)
XEVT(_T("PSP_RTLREADING"),PSP_RTLREADING,0x00000010)

XEVT(_T("PSP_HASHELP"),PSP_HASHELP,0x00000020)
XEVT(_T("PSP_USEREFPARENT"),PSP_USEREFPARENT,0x00000040)
XEVT(_T("PSP_USECALLBACK"),PSP_USECALLBACK,0x00000080)
XEVT(_T("PSP_PREMATURE"),PSP_PREMATURE,0x00000400)

#if (_WIN32_IE >= 0x0400)
//----- New flags for wizard97 --------------
XEVT(_T("PSP_HIDEHEADER"),PSP_HIDEHEADER,0x00000800)
XEVT(_T("PSP_USEHEADERTITLE"),PSP_USEHEADERTITLE,0x00001000)
XEVT(_T("PSP_USEHEADERSUBTITLE"),PSP_USEHEADERSUBTITLE,0x00002000)
//-------------------------------------------
#endif
#if (_WIN32_WINNT >= 0x0501) || ISOLATION_AWARE_ENABLED
XEVT(_T("PSP_USEFUSIONCONTEXT"),PSP_USEFUSIONCONTEXT,0x00004000)
#endif

//====== HEADER CONTROL =======================================================
XEVT(_T("header.ITEMCHANGINGA"),HDN_ITEMCHANGINGA,(HDN_FIRST-0))
XEVT(_T("header.ITEMCHANGINGW"),HDN_ITEMCHANGINGW,(HDN_FIRST-20))
XEVT(_T("header.ITEMCHANGEDA"),HDN_ITEMCHANGEDA,(HDN_FIRST-1))
XEVT(_T("header.ITEMCHANGEDW"),HDN_ITEMCHANGEDW,(HDN_FIRST-21))
XEVT(_T("header.ITEMCLICKA"),HDN_ITEMCLICKA,(HDN_FIRST-2))
XEVT(_T("header.ITEMCLICKW"),HDN_ITEMCLICKW,(HDN_FIRST-22))
XEVT(_T("header.ITEMDBLCLICKA"),HDN_ITEMDBLCLICKA,(HDN_FIRST-3))
XEVT(_T("header.ITEMDBLCLICKW"),HDN_ITEMDBLCLICKW,(HDN_FIRST-23))
XEVT(_T("header.DIVIDERDBLCLICKA"),HDN_DIVIDERDBLCLICKA,(HDN_FIRST-5))
XEVT(_T("header.DIVIDERDBLCLICKW"),HDN_DIVIDERDBLCLICKW,(HDN_FIRST-25))
XEVT(_T("header.BEGINTRACKA"),HDN_BEGINTRACKA,(HDN_FIRST-6))
XEVT(_T("header.BEGINTRACKW"),HDN_BEGINTRACKW,(HDN_FIRST-26))
XEVT(_T("header.ENDTRACKA"),HDN_ENDTRACKA,(HDN_FIRST-7))
XEVT(_T("header.ENDTRACKW"),HDN_ENDTRACKW,(HDN_FIRST-27))
XEVT(_T("header.TRACKA"),HDN_TRACKA,(HDN_FIRST-8))
XEVT(_T("header.TRACKW"),HDN_TRACKW,(HDN_FIRST-28))
#if (_WIN32_IE >= 0x0300)
XEVT(_T("header.GETDISPINFOA"),HDN_GETDISPINFOA,(HDN_FIRST-9))
XEVT(_T("header.GETDISPINFOW"),HDN_GETDISPINFOW,(HDN_FIRST-29))
XEVT(_T("header.BEGINDRAG"),HDN_BEGINDRAG,(HDN_FIRST-10))
XEVT(_T("header.ENDDRAG"),HDN_ENDDRAG,(HDN_FIRST-11))
#endif
#if (_WIN32_IE >= 0x0500)
XEVT(_T("header.FILTERCHANGE"),HDN_FILTERCHANGE,(HDN_FIRST-12))
XEVT(_T("header.FILTERBTNCLICK"),HDN_FILTERBTNCLICK,(HDN_FIRST-13))
#endif

#ifdef UNICODE
XEVT(_T("header.ITEMCHANGING"),HDN_ITEMCHANGING,HDN_ITEMCHANGINGW)
XEVT(_T("header.ITEMCHANGED"),HDN_ITEMCHANGED,HDN_ITEMCHANGEDW)
XEVT(_T("header.ITEMCLICK"),HDN_ITEMCLICK,HDN_ITEMCLICKW)
XEVT(_T("header.ITEMDBLCLICK"),HDN_ITEMDBLCLICK,HDN_ITEMDBLCLICKW)
XEVT(_T("header.DIVIDERDBLCLICK"),HDN_DIVIDERDBLCLICK,HDN_DIVIDERDBLCLICKW)
XEVT(_T("header.BEGINTRACK"),HDN_BEGINTRACK,HDN_BEGINTRACKW)
XEVT(_T("header.ENDTRACK"),HDN_ENDTRACK,HDN_ENDTRACKW)
XEVT(_T("header.TRACK"),HDN_TRACK,HDN_TRACKW)
#if (_WIN32_IE >= 0x0300)
XEVT(_T("header.GETDISPINFO"),HDN_GETDISPINFO,HDN_GETDISPINFOW)
#endif
#else
XEVT(_T("header.ITEMCHANGING"),HDN_ITEMCHANGING,HDN_ITEMCHANGINGA)
XEVT(_T("header.ITEMCHANGED"),HDN_ITEMCHANGED,HDN_ITEMCHANGEDA)
XEVT(_T("header.ITEMCLICK"),HDN_ITEMCLICK,HDN_ITEMCLICKA)
XEVT(_T("header.ITEMDBLCLICK"),HDN_ITEMDBLCLICK,HDN_ITEMDBLCLICKA)
XEVT(_T("header.DIVIDERDBLCLICK"),HDN_DIVIDERDBLCLICK,HDN_DIVIDERDBLCLICKA)
XEVT(_T("header.BEGINTRACK"),HDN_BEGINTRACK,HDN_BEGINTRACKA)
XEVT(_T("header.ENDTRACK"),HDN_ENDTRACK,HDN_ENDTRACKA)
XEVT(_T("header.TRACK"),HDN_TRACK,HDN_TRACKA)
#if (_WIN32_IE >= 0x0300)
XEVT(_T("header.GETDISPINFO"),HDN_GETDISPINFO,HDN_GETDISPINFOA)
#endif
#endif

//====== TOOLBAR CONTROL ======================================================
XEVT(_T("TBN_GETBUTTONINFOA"),TBN_GETBUTTONINFOA,(TBN_FIRST-0))
XEVT(_T("TBN_BEGINDRAG"),TBN_BEGINDRAG,(TBN_FIRST-1))
XEVT(_T("TBN_ENDDRAG"),TBN_ENDDRAG,(TBN_FIRST-2))
XEVT(_T("TBN_BEGINADJUST"),TBN_BEGINADJUST,(TBN_FIRST-3))
XEVT(_T("TBN_ENDADJUST"),TBN_ENDADJUST,(TBN_FIRST-4))
XEVT(_T("TBN_RESET"),TBN_RESET,(TBN_FIRST-5))
XEVT(_T("TBN_QUERYINSERT"),TBN_QUERYINSERT,(TBN_FIRST-6))
XEVT(_T("TBN_QUERYDELETE"),TBN_QUERYDELETE,(TBN_FIRST-7))
XEVT(_T("TBN_TOOLBARCHANGE"),TBN_TOOLBARCHANGE,(TBN_FIRST-8))
XEVT(_T("TBN_CUSTHELP"),TBN_CUSTHELP,(TBN_FIRST-9))
#if (_WIN32_IE >= 0x0300)
XEVT(_T("TBN_DROPDOWN"),TBN_DROPDOWN,(TBN_FIRST - 10))
#endif
#if (_WIN32_IE >= 0x0400)
XEVT(_T("TBN_GETOBJECT"),TBN_GETOBJECT,(TBN_FIRST - 12))
#endif

XEVT(_T("TBN_HOTITEMCHANGE"),TBN_HOTITEMCHANGE,(TBN_FIRST - 13))
XEVT(_T("TBN_DRAGOUT"),TBN_DRAGOUT,(TBN_FIRST - 14)) // this is sent when the user clicks down on a button then drags off the button
XEVT(_T("TBN_DELETINGBUTTON"),TBN_DELETINGBUTTON,(TBN_FIRST - 15)) // uses TBNOTIFY
XEVT(_T("TBN_GETDISPINFOA"),TBN_GETDISPINFOA,(TBN_FIRST - 16)) // This is sent when the  toolbar needs  some display information
XEVT(_T("TBN_GETDISPINFOW"),TBN_GETDISPINFOW,(TBN_FIRST - 17)) // This is sent when the  toolbar needs  some display information
XEVT(_T("TBN_GETINFOTIPA"),TBN_GETINFOTIPA,(TBN_FIRST - 18))
XEVT(_T("TBN_GETINFOTIPW"),TBN_GETINFOTIPW,(TBN_FIRST - 19))
XEVT(_T("TBN_GETBUTTONINFOW"),TBN_GETBUTTONINFOW,(TBN_FIRST - 20))
#if (_WIN32_IE >= 0x0500)
XEVT(_T("TBN_RESTORE"),TBN_RESTORE,(TBN_FIRST - 21))
XEVT(_T("TBN_SAVE"),TBN_SAVE,(TBN_FIRST - 22))
XEVT(_T("TBN_INITCUSTOMIZE"),TBN_INITCUSTOMIZE,(TBN_FIRST - 23))
#endif // (_WIN32_IE >= 0x0500)

#ifdef UNICODE
XEVT(_T("TBN_GETINFOTIP"),TBN_GETINFOTIP,TBN_GETINFOTIPW)
#else
XEVT(_T("TBN_GETINFOTIP"),TBN_GETINFOTIP,TBN_GETINFOTIPA)
#endif

#ifdef UNICODE
XEVT(_T("TBN_GETDISPINFO"),TBN_GETDISPINFO,TBN_GETDISPINFOW)
#else
XEVT(_T("TBN_GETDISPINFO"),TBN_GETDISPINFO,TBN_GETDISPINFOA)
#endif

#ifdef UNICODE
XEVT(_T("TBN_GETBUTTONINFO"),TBN_GETBUTTONINFO,TBN_GETBUTTONINFOW)
#else
XEVT(_T("TBN_GETBUTTONINFO"),TBN_GETBUTTONINFO,TBN_GETBUTTONINFOA)
#endif


//====== REBAR CONTROL ========================================================
XEVT(_T("RBN_HEIGHTCHANGE"),RBN_HEIGHTCHANGE,(RBN_FIRST - 0))

XEVT(_T("RBN_GETOBJECT"),RBN_GETOBJECT,(RBN_FIRST - 1))
XEVT(_T("RBN_LAYOUTCHANGED"),RBN_LAYOUTCHANGED,(RBN_FIRST - 2))
XEVT(_T("RBN_AUTOSIZE"),RBN_AUTOSIZE,(RBN_FIRST - 3))
XEVT(_T("RBN_BEGINDRAG"),RBN_BEGINDRAG,(RBN_FIRST - 4))
XEVT(_T("RBN_ENDDRAG"),RBN_ENDDRAG,(RBN_FIRST - 5))
XEVT(_T("RBN_DELETINGBAND"),RBN_DELETINGBAND,(RBN_FIRST - 6))     // Uses NMREBAR
XEVT(_T("RBN_DELETEDBAND"),RBN_DELETEDBAND,(RBN_FIRST - 7))     // Uses NMREBAR
XEVT(_T("RBN_CHILDSIZE"),RBN_CHILDSIZE,(RBN_FIRST - 8))

#if (_WIN32_IE >= 0x0500)
XEVT(_T("RBN_CHEVRONPUSHED"),RBN_CHEVRONPUSHED,(RBN_FIRST - 10))
#endif      // _WIN32_IE >= 0x0500


#if (_WIN32_IE >= 0x0500)
XEVT(_T("RBN_MINMAX"),RBN_MINMAX,(RBN_FIRST - 21))
#endif

#if (_WIN32_WINNT >= 0x0501)
XEVT(_T("RBN_AUTOBREAK"),RBN_AUTOBREAK,(RBN_FIRST - 22))
#endif


//====== TOOLTIPS CONTROL =====================================================
XEVT(_T("toolbar.GETDISPINFOA"),TTN_GETDISPINFOA,(TTN_FIRST - 0))
XEVT(_T("toolbar.GETDISPINFOW"),TTN_GETDISPINFOW,(TTN_FIRST - 10))
XEVT(_T("toolbar.SHOW"),TTN_SHOW,(TTN_FIRST - 1))
XEVT(_T("toolbar.POP"),TTN_POP,(TTN_FIRST - 2))
XEVT(_T("toolbar.LINKCLICK"),TTN_LINKCLICK,(TTN_FIRST - 3))

#ifdef UNICODE
XEVT(_T("toolbar.GETDISPINFO"),TTN_GETDISPINFO,TTN_GETDISPINFOW)
#else
XEVT(_T("toolbar.GETDISPINFO"),TTN_GETDISPINFO,TTN_GETDISPINFOA)
#endif

XEVT(_T("toolbar.NEEDTEXT"),TTN_NEEDTEXT,TTN_GETDISPINFO)
XEVT(_T("toolbar.NEEDTEXTA"),TTN_NEEDTEXTA,TTN_GETDISPINFOA)
XEVT(_T("toolbar.NEEDTEXTW"),TTN_NEEDTEXTW,TTN_GETDISPINFOW)

//====== STATUS BAR CONTROL ===================================================
/// status bar notifications
#if (_WIN32_IE >= 0x0400)
XEVT(_T("SBN_SIMPLEMODECHANGE"),SBN_SIMPLEMODECHANGE,(SBN_FIRST - 0))
#endif

//====== MENU HELP ============================================================

//====== TRACKBAR CONTROL =====================================================
//====== DRAG LIST CONTROL ====================================================
//====== UPDOWN CONTROL =======================================================
XEVT(_T("UDN_DELTAPOS"),UDN_DELTAPOS,(UDN_FIRST - 1))

//====== PROGRESS CONTROL =====================================================
//====== HOTKEY CONTROL =======================================================
//====== COMMON CONTROL STYLES ================================================
//====== LISTVIEW CONTROL =====================================================
XEVT(_T("listview.ITEMCHANGING"),LVN_ITEMCHANGING,(LVN_FIRST-0))
XEVT(_T("listview.ITEMCHANGED"),LVN_ITEMCHANGED,(LVN_FIRST-1))
XEVT(_T("listview.INSERTITEM"),LVN_INSERTITEM,(LVN_FIRST-2))
XEVT(_T("listview.DELETEITEM"),LVN_DELETEITEM,(LVN_FIRST-3))
XEVT(_T("listview.DELETEALLITEMS"),LVN_DELETEALLITEMS,(LVN_FIRST-4))
XEVT(_T("listview.BEGINLABELEDITA"),LVN_BEGINLABELEDITA,(LVN_FIRST-5))
XEVT(_T("listview.BEGINLABELEDITW"),LVN_BEGINLABELEDITW,(LVN_FIRST-75))
XEVT(_T("listview.ENDLABELEDITA"),LVN_ENDLABELEDITA,(LVN_FIRST-6))
XEVT(_T("listview.ENDLABELEDITW"),LVN_ENDLABELEDITW,(LVN_FIRST-76))
XEVT(_T("listview.COLUMNCLICK"),LVN_COLUMNCLICK,(LVN_FIRST-8))
XEVT(_T("listview.BEGINDRAG"),LVN_BEGINDRAG,(LVN_FIRST-9))
XEVT(_T("listview.BEGINRDRAG"),LVN_BEGINRDRAG,(LVN_FIRST-11))

#if (_WIN32_IE >= 0x0300)
XEVT(_T("listview.ODCACHEHINT"),LVN_ODCACHEHINT,(LVN_FIRST-13))
XEVT(_T("listview.ODFINDITEMA"),LVN_ODFINDITEMA,(LVN_FIRST-52))
XEVT(_T("listview.ODFINDITEMW"),LVN_ODFINDITEMW,(LVN_FIRST-79))

XEVT(_T("listview.ITEMACTIVATE"),LVN_ITEMACTIVATE,(LVN_FIRST-14))
XEVT(_T("listview.ODSTATECHANGED"),LVN_ODSTATECHANGED,(LVN_FIRST-15))

#ifdef UNICODE
XEVT(_T("listview.ODFINDITEM"),LVN_ODFINDITEM,LVN_ODFINDITEMW)
#else
XEVT(_T("listview.ODFINDITEM"),LVN_ODFINDITEM,LVN_ODFINDITEMA)
#endif
#endif      // _WIN32_IE >= 0x0300


#if (_WIN32_IE >= 0x0400)
XEVT(_T("listview.HOTTRACK"),LVN_HOTTRACK,(LVN_FIRST-21))
#endif

XEVT(_T("listview.GETDISPINFOA"),LVN_GETDISPINFOA,(LVN_FIRST-50))
XEVT(_T("listview.GETDISPINFOW"),LVN_GETDISPINFOW,(LVN_FIRST-77))
XEVT(_T("listview.SETDISPINFOA"),LVN_SETDISPINFOA,(LVN_FIRST-51))
XEVT(_T("listview.SETDISPINFOW"),LVN_SETDISPINFOW,(LVN_FIRST-78))

#ifdef UNICODE
XEVT(_T("listview.BEGINLABELEDIT"),LVN_BEGINLABELEDIT,LVN_BEGINLABELEDITW)
XEVT(_T("listview.ENDLABELEDIT"),LVN_ENDLABELEDIT,LVN_ENDLABELEDITW)
XEVT(_T("listview.GETDISPINFO"),LVN_GETDISPINFO,LVN_GETDISPINFOW)
XEVT(_T("listview.SETDISPINFO"),LVN_SETDISPINFO,LVN_SETDISPINFOW)
#else
XEVT(_T("listview.BEGINLABELEDIT"),LVN_BEGINLABELEDIT,LVN_BEGINLABELEDITA)
XEVT(_T("listview.ENDLABELEDIT"),LVN_ENDLABELEDIT,LVN_ENDLABELEDITA)
XEVT(_T("listview.GETDISPINFO"),LVN_GETDISPINFO,LVN_GETDISPINFOA)
XEVT(_T("listview.SETDISPINFO"),LVN_SETDISPINFO,LVN_SETDISPINFOA)
#endif


XEVT(_T("listview.GETINFOTIPA"),LVN_GETINFOTIPA,(LVN_FIRST-57))
XEVT(_T("listview.GETINFOTIPW"),LVN_GETINFOTIPW,(LVN_FIRST-58))

#ifdef UNICODE
XEVT(_T("listview.GETINFOTIP"),LVN_GETINFOTIP,LVN_GETINFOTIPW)
#else
XEVT(_T("listview.GETINFOTIP"),LVN_GETINFOTIP,LVN_GETINFOTIPA)
#endif

XEVT(_T("listview.BEGINSCROLL"),LVN_BEGINSCROLL,(LVN_FIRST-80))          
XEVT(_T("listview.ENDSCROLL"),LVN_ENDSCROLL,(LVN_FIRST-81))

//====== TREEVIEW CONTROL =====================================================
XEVT(_T("treeview.SELCHANGINGA"),TVN_SELCHANGINGA,(TVN_FIRST-1))
XEVT(_T("treeview.SELCHANGINGW"),TVN_SELCHANGINGW,(TVN_FIRST-50))
XEVT(_T("treeview.SELCHANGEDA"),TVN_SELCHANGEDA,(TVN_FIRST-2))
XEVT(_T("treeview.SELCHANGEDW"),TVN_SELCHANGEDW,(TVN_FIRST-51))

XEVT(_T("treeview.GETDISPINFOA"),TVN_GETDISPINFOA,(TVN_FIRST-3))
XEVT(_T("treeview.GETDISPINFOW"),TVN_GETDISPINFOW,(TVN_FIRST-52))
XEVT(_T("treeview.SETDISPINFOA"),TVN_SETDISPINFOA,(TVN_FIRST-4))
XEVT(_T("treeview.SETDISPINFOW"),TVN_SETDISPINFOW,(TVN_FIRST-53))

XEVT(_T("treeview.ITEMEXPANDINGA"),TVN_ITEMEXPANDINGA,(TVN_FIRST-5))
XEVT(_T("treeview.ITEMEXPANDINGW"),TVN_ITEMEXPANDINGW,(TVN_FIRST-54))
XEVT(_T("treeview.ITEMEXPANDEDA"),TVN_ITEMEXPANDEDA,(TVN_FIRST-6))
XEVT(_T("treeview.ITEMEXPANDEDW"),TVN_ITEMEXPANDEDW,(TVN_FIRST-55))
XEVT(_T("treeview.BEGINDRAGA"),TVN_BEGINDRAGA,(TVN_FIRST-7))
XEVT(_T("treeview.BEGINDRAGW"),TVN_BEGINDRAGW,(TVN_FIRST-56))
XEVT(_T("treeview.BEGINRDRAGA"),TVN_BEGINRDRAGA,(TVN_FIRST-8))
XEVT(_T("treeview.BEGINRDRAGW"),TVN_BEGINRDRAGW,(TVN_FIRST-57))
XEVT(_T("treeview.DELETEITEMA"),TVN_DELETEITEMA,(TVN_FIRST-9))
XEVT(_T("treeview.DELETEITEMW"),TVN_DELETEITEMW,(TVN_FIRST-58))
XEVT(_T("treeview.BEGINLABELEDITA"),TVN_BEGINLABELEDITA,(TVN_FIRST-10))
XEVT(_T("treeview.BEGINLABELEDITW"),TVN_BEGINLABELEDITW,(TVN_FIRST-59))
XEVT(_T("treeview.ENDLABELEDITA"),TVN_ENDLABELEDITA,(TVN_FIRST-11))
XEVT(_T("treeview.ENDLABELEDITW"),TVN_ENDLABELEDITW,(TVN_FIRST-60))
XEVT(_T("treeview.KEYDOWN"),TVN_KEYDOWN,(TVN_FIRST-12))

#if (_WIN32_IE >= 0x0400)
XEVT(_T("treeview.GETINFOTIPA"),TVN_GETINFOTIPA,(TVN_FIRST-13))
XEVT(_T("treeview.GETINFOTIPW"),TVN_GETINFOTIPW,(TVN_FIRST-14))
XEVT(_T("treeview.SINGLEEXPAND"),TVN_SINGLEEXPAND,(TVN_FIRST-15))

#endif // 0x400

#ifdef UNICODE
XEVT(_T("treeview.SELCHANGING"),TVN_SELCHANGING,TVN_SELCHANGINGW)
XEVT(_T("treeview.SELCHANGED"),TVN_SELCHANGED,TVN_SELCHANGEDW)
XEVT(_T("treeview.GETDISPINFO"),TVN_GETDISPINFO,TVN_GETDISPINFOW)
XEVT(_T("treeview.SETDISPINFO"),TVN_SETDISPINFO,TVN_SETDISPINFOW)
XEVT(_T("treeview.ITEMEXPANDING"),TVN_ITEMEXPANDING,TVN_ITEMEXPANDINGW)
XEVT(_T("treeview.ITEMEXPANDED"),TVN_ITEMEXPANDED,TVN_ITEMEXPANDEDW)
XEVT(_T("treeview.BEGINDRAG"),TVN_BEGINDRAG,TVN_BEGINDRAGW)
XEVT(_T("treeview.BEGINRDRAG"),TVN_BEGINRDRAG,TVN_BEGINRDRAGW)
XEVT(_T("treeview.DELETEITEM"),TVN_DELETEITEM,TVN_DELETEITEMW)
XEVT(_T("treeview.BEGINLABELEDIT"),TVN_BEGINLABELEDIT,TVN_BEGINLABELEDITW)
XEVT(_T("treeview.ENDLABELEDIT"),TVN_ENDLABELEDIT,TVN_ENDLABELEDITW)
#else
XEVT(_T("treeview.SELCHANGING"),TVN_SELCHANGING,TVN_SELCHANGINGA)
XEVT(_T("treeview.SELCHANGED"),TVN_SELCHANGED,TVN_SELCHANGEDA)
XEVT(_T("treeview.GETDISPINFO"),TVN_GETDISPINFO,TVN_GETDISPINFOA)
XEVT(_T("treeview.SETDISPINFO"),TVN_SETDISPINFO,TVN_SETDISPINFOA)
XEVT(_T("treeview.ITEMEXPANDING"),TVN_ITEMEXPANDING,TVN_ITEMEXPANDINGA)
XEVT(_T("treeview.ITEMEXPANDED"),TVN_ITEMEXPANDED,TVN_ITEMEXPANDEDA)
XEVT(_T("treeview.BEGINDRAG"),TVN_BEGINDRAG,TVN_BEGINDRAGA)
XEVT(_T("treeview.BEGINRDRAG"),TVN_BEGINRDRAG,TVN_BEGINRDRAGA)
XEVT(_T("treeview.DELETEITEM"),TVN_DELETEITEM,TVN_DELETEITEMA)
XEVT(_T("treeview.BEGINLABELEDIT"),TVN_BEGINLABELEDIT,TVN_BEGINLABELEDITA)
XEVT(_T("treeview.ENDLABELEDIT"),TVN_ENDLABELEDIT,TVN_ENDLABELEDITA)
#endif

#ifdef UNICODE
XEVT(_T("treeview.GETINFOTIP"),TVN_GETINFOTIP,TVN_GETINFOTIPW)
#else
XEVT(_T("treeview.GETINFOTIP"),TVN_GETINFOTIP,TVN_GETINFOTIPA)
#endif

////////////////////  ComboBoxEx ////////////////////////////////
XEVT(_T("CBEN_GETDISPINFOW"),CBEN_GETDISPINFOW,(CBEN_FIRST - 7))
XEVT(_T("CBEN_GETDISPINFOA"),CBEN_GETDISPINFOA,(CBEN_FIRST - 0))
#ifdef UNICODE
XEVT(_T("CBEN_GETDISPINFO"),CBEN_GETDISPINFO,CBEN_GETDISPINFOW)
#else
XEVT(_T("CBEN_GETDISPINFO"),CBEN_GETDISPINFO,CBEN_GETDISPINFOA)
#endif

XEVT(_T("CBEN_INSERTITEM"),CBEN_INSERTITEM,(CBEN_FIRST - 1))
XEVT(_T("CBEN_DELETEITEM"),CBEN_DELETEITEM,(CBEN_FIRST - 2))
XEVT(_T("CBEN_BEGINEDIT"),CBEN_BEGINEDIT,(CBEN_FIRST - 4))
XEVT(_T("CBEN_ENDEDITA"),CBEN_ENDEDITA,(CBEN_FIRST - 5))
XEVT(_T("CBEN_ENDEDITW"),CBEN_ENDEDITW,(CBEN_FIRST - 6))

XEVT(_T("CBEN_DRAGBEGINA"),CBEN_DRAGBEGINA,(CBEN_FIRST - 8))
XEVT(_T("CBEN_DRAGBEGINW"),CBEN_DRAGBEGINW,(CBEN_FIRST - 9))

#ifdef UNICODE
XEVT(_T("CBEN_DRAGBEGIN"),CBEN_DRAGBEGIN,CBEN_DRAGBEGINW)
#else
XEVT(_T("CBEN_DRAGBEGIN"),CBEN_DRAGBEGIN,CBEN_DRAGBEGINA)
#endif
// lParam specifies why the endedit is happening
#ifdef UNICODE
XEVT(_T("CBEN_ENDEDIT"),CBEN_ENDEDIT,CBEN_ENDEDITW)
#else
XEVT(_T("CBEN_ENDEDIT"),CBEN_ENDEDIT,CBEN_ENDEDITA)
#endif

//====== TAB CONTROL ==========================================================
XEVT(_T("tab.KEYDOWN"),TCN_KEYDOWN,(TCN_FIRST - 0))
XEVT(_T("tab.SELCHANGE"),TCN_SELCHANGE,(TCN_FIRST - 1))
XEVT(_T("tab.SELCHANGING"),TCN_SELCHANGING,(TCN_FIRST - 2))
#if (_WIN32_IE >= 0x0400)
XEVT(_T("tab.GETOBJECT"),TCN_GETOBJECT,(TCN_FIRST - 3))
#endif      // _WIN32_IE >= 0x0400
#if (_WIN32_IE >= 0x0500)
XEVT(_T("tab.FOCUSCHANGE"),TCN_FOCUSCHANGE,(TCN_FIRST - 4))
#endif      // _WIN32_IE >= 0x0500


//====== ANIMATE CONTROL ======================================================
XEVT(_T("ACN_START"),ACN_START,1)
XEVT(_T("ACN_STOP"),ACN_STOP,2)

//====== MONTHCAL CONTROL ======================================================
XEVT(_T("MCN_SELCHANGE"),MCN_SELCHANGE,(MCN_FIRST + 1))
XEVT(_T("MCN_GETDAYSTATE"),MCN_GETDAYSTATE,(MCN_FIRST + 3))
XEVT(_T("MCN_SELECT"),MCN_SELECT,(MCN_FIRST + 4))

//====== DATETIMEPICK CONTROL ==================================================
#ifdef UNICODE
XEVT(_T("DTN_WMKEYDOWN"),DTN_WMKEYDOWN,DTN_WMKEYDOWNW)
#else
XEVT(_T("DTN_WMKEYDOWN"),DTN_WMKEYDOWN,DTN_WMKEYDOWNA)
#endif


XEVT(_T("DTN_FORMATA"),DTN_FORMATA,(DTN_FIRST + 4)) 
XEVT(_T("DTN_FORMATW"),DTN_FORMATW,(DTN_FIRST + 17))

#ifdef UNICODE
XEVT(_T("DTN_FORMAT"),DTN_FORMAT,DTN_FORMATW)
#else
XEVT(_T("DTN_FORMAT"),DTN_FORMAT,DTN_FORMATA)
#endif


XEVT(_T("DTN_FORMATQUERYA"),DTN_FORMATQUERYA,(DTN_FIRST + 5))
XEVT(_T("DTN_FORMATQUERYW"),DTN_FORMATQUERYW,(DTN_FIRST + 18))

#ifdef UNICODE
XEVT(_T("DTN_FORMATQUERY"),DTN_FORMATQUERY,DTN_FORMATQUERYW)
#else
XEVT(_T("DTN_FORMATQUERY"),DTN_FORMATQUERY,DTN_FORMATQUERYA)
#endif

XEVT(_T("DTN_DROPDOWN"),DTN_DROPDOWN,(DTN_FIRST + 6)) // MonthCal has dropped down
XEVT(_T("DTN_CLOSEUP"),DTN_CLOSEUP,(DTN_FIRST + 7)) // MonthCal is popping up


//    IP Address edit control
XEVT(_T("IPN_FIELDCHANGED"),IPN_FIELDCHANGED,(IPN_FIRST - 0))

//  ====================== Pager Control =============================
XEVT(_T("PGN_CALCSIZE"),PGN_CALCSIZE,(PGN_FIRST-2))
XEVT(_T("PGN_HOTITEMCHANGE"),PGN_HOTITEMCHANGE,(PGN_FIRST-3))


// === Native Font Control ===
/// ====================== Button Control =============================
XEVT(_T("BN_CLICKED"),BN_CLICKED,0)
XEVT(_T("BN_PAINT"),BN_PAINT,1)
XEVT(_T("BN_HILITE"),BN_HILITE,2)
XEVT(_T("BN_UNHILITE"),BN_UNHILITE,3)
XEVT(_T("BN_DISABLE"),BN_DISABLE,4)
XEVT(_T("BN_DOUBLECLICKED"),BN_DOUBLECLICKED,5)
#if(WINVER >= 0x0400)
XEVT(_T("BN_PUSHED"),BN_PUSHED,BN_HILITE)
XEVT(_T("BN_UNPUSHED"),BN_UNPUSHED,BN_UNHILITE)
XEVT(_T("BN_DBLCLK"),BN_DBLCLK,BN_DOUBLECLICKED)
XEVT(_T("BN_SETFOCUS"),BN_SETFOCUS,6)
XEVT(_T("BN_KILLFOCUS"),BN_KILLFOCUS,7)
#endif /* WINVER >= 0x0400 */

/// ====================== Static Control =============================
XEVT(_T("STN_CLICKED"),STN_CLICKED,0)
XEVT(_T("STN_DBLCLK"),STN_DBLCLK,1)
XEVT(_T("STN_ENABLE"),STN_ENABLE,2)
XEVT(_T("STN_DISABLE"),STN_DISABLE,3)

/// ====================== Edit Control =============================
/*
 * Edit Control Notification Codes
 */
XEVT(_T("EN_SETFOCUS"),EN_SETFOCUS,0x0100)
XEVT(_T("EN_KILLFOCUS"),EN_KILLFOCUS,0x0200)
XEVT(_T("EN_CHANGE"),EN_CHANGE,0x0300)
XEVT(_T("EN_UPDATE"),EN_UPDATE,0x0400)
XEVT(_T("EN_ERRSPACE"),EN_ERRSPACE,0x0500)
XEVT(_T("EN_MAXTEXT"),EN_MAXTEXT,0x0501)
XEVT(_T("EN_HSCROLL"),EN_HSCROLL,0x0601)
XEVT(_T("EN_VSCROLL"),EN_VSCROLL,0x0602)

#if(_WIN32_WINNT >= 0x0500)
XEVT(_T("EN_ALIGN_LTR_EC"),EN_ALIGN_LTR_EC,0x0700)
XEVT(_T("EN_ALIGN_RTL_EC"),EN_ALIGN_RTL_EC,0x0701)
#endif /* _WIN32_WINNT >= 0x0500 */
/// ====================== Listbox Control =============================
XEVT(_T("LBN_ERRSPACE"),LBN_ERRSPACE,(-2))
XEVT(_T("LBN_SELCHANGE"),LBN_SELCHANGE,1)
XEVT(_T("LBN_DBLCLK"),LBN_DBLCLK,2)
XEVT(_T("LBN_SELCANCEL"),LBN_SELCANCEL,3)
XEVT(_T("LBN_SETFOCUS"),LBN_SETFOCUS,4)
XEVT(_T("LBN_KILLFOCUS"),LBN_KILLFOCUS,5)

/// ====================== Combobox Control =============================
XEVT(_T("CBN_ERRSPACE"),CBN_ERRSPACE,(-1))
XEVT(_T("CBN_SELCHANGE"),CBN_SELCHANGE,1)
XEVT(_T("CBN_DBLCLK"),CBN_DBLCLK,2)
XEVT(_T("CBN_SETFOCUS"),CBN_SETFOCUS,3)
XEVT(_T("CBN_KILLFOCUS"),CBN_KILLFOCUS,4)
XEVT(_T("CBN_EDITCHANGE"),CBN_EDITCHANGE,5)
XEVT(_T("CBN_EDITUPDATE"),CBN_EDITUPDATE,6)
XEVT(_T("CBN_DROPDOWN"),CBN_DROPDOWN,7)
XEVT(_T("CBN_CLOSEUP"),CBN_CLOSEUP,8)
XEVT(_T("CBN_SELENDOK"),CBN_SELENDOK,9)
XEVT(_T("CBN_SELENDCANCEL"),CBN_SELENDCANCEL,10)
/// ====================== Scrollbar Control ============================

//====== SysLink control =========================================
// === MUI APIs ===
//====== TrackMouseEvent  =====================================================
#ifndef WM_MOUSEHOVER
XEVT(_T("window.MOUSEHOVER"),WM_MOUSEHOVER,0x02A1)
XEVT(_T("window.MOUSELEAVE"),WM_MOUSELEAVE,0x02A3)
#endif
//====== Flat Scrollbar APIs=========================================

//OWNER
XEVT(_T("window.XCOMMAND"),WM_XCOMMAND,	 (WM_USER + 0x01))
XEVT(_T("window.FOCUSNEXT"),WM_FOCUSNEXT,(WM_USER + 0x02))
XEVT(_T("window.FOCUSPREV"),WM_FOCUSPREV, (WM_USER + 0x03))
